### ISSUE TITLE
Debugtoolbar panel template static path bug

### ISSUE THREAD

**Issue by lutanist** [MongoEngine/flask-mongoengine#109]
fix from
```html
<script type="text/javascript" src="/_debug_toolbar/static/js/jquery.js"></script>
```
to
```html
<script type="text/javascript" src="{{ static_path }}js/jquery.js"></script>
```

**Comment by lafrech** [comment]
This appears in 

    ./build/lib/flask_mongoengine/templates/panels/mongo-panel.html

but not in

    flask_mongoengine/templates/panels/mongo-panel.html

I'm not familiar with the build process. Any idea how to improve this?

Pull-request welcome, of course.

**Comment by lafrech** [comment]
This appears in 

    ./build/lib/flask_mongoengine/templates/panels/mongo-panel.html

but not in 

    flask_mongoengine/templates/panels/mongo-panel.html

I'm not familiar with the build process. Any idea how to improve this?

Pull-request welcome, of course.

**Comment by lafrech** [comment]
Is this still relevant? Fixed by https://github.com/MongoEngine/flask-mongoengine/commit/932ea83de27a2544023f378d33841ddf162d4af9?

**Comment by losintikfos** [comment]
@lafrech yes it is - thanks.

**Comment by lafrech** [comment]
I guess you mean it is fixed, not relevant. Closing.
