### ISSUE TITLE
Allow read preference setup

### ISSUE THREAD

**Issue by italomaia** [MongoEngine/flask-mongoengine#132]
As title says.

**Comment by rturk** [comment]
+1

Currently Flask-mongoengine alredy supports:

    MONGODB_DB 
    MONGODB_HOST

Missing additional setting

    MONOGODB_READ_PREFERENCE

**Comment by sibeliusseraphini** [comment]
@lafrech any workaround to set mongodb read preference?

**Comment by lafrech** [comment]
Reading the code, it looks like it would work by just patching `init_app` [here](https://github.com/MongoEngine/flask-mongoengine/blob/60f8704cfa0226fe2ba9e49288fe64bd949a511b/flask_mongoengine/__init__.py#L137):

            # Connection settings provided in standard format.
            settings = {'alias': config.get('MONGODB_ALIAS', None),
                        'db': config.get('MONGODB_DB', None),
                        'host': config.get('MONGODB_HOST', None),
                        'password': config.get('MONGODB_PASSWORD', None),
                        'port': config.get('MONGODB_PORT', None),
                        'username': config.get('MONGODB_USERNAME', None)}
            connection = _create_connection(settings)

Add a `read_preference` option:

            # Connection settings provided in standard format.
            settings = {'alias': config.get('MONGODB_ALIAS', None),
                        'db': config.get('MONGODB_DB', None),
                        'host': config.get('MONGODB_HOST', None),
                        'password': config.get('MONGODB_PASSWORD', None),
                        'port': config.get('MONGODB_PORT', None),
                        'username': config.get('MONGODB_USERNAME', None)}
                        'read_preference': config.get('MONGODB_READ_PREFERENCE', None)}
            connection = _create_connection(settings)

Would you like to try that and submit a PR?

A workaround would be to submit the options as a dict that would include the `read_preference` key:

        if 'MONGODB_SETTINGS' in config:
            # Connection settings provided as a dictionary.
            connection = _create_connection(config['MONGODB_SETTINGS'])

**Comment by wojcikstefan** [comment]
`READ_PREFERENCE` can be included in `MONGODB_SETTINGS` already. See e.g. https://github.com/MongoEngine/flask-mongoengine/blob/b5b4609931a48a8982f81a227c3ef91740886964/tests/test_connection.py#L136
