### ISSUE TITLE
Error connecting to MongoDB

### ISSUE THREAD

**Issue by dpgaspar** [MongoEngine/flask-mongoengine#136]
I think this is happening on pymongo new release:

http://stackoverflow.com/questions/29517930/error-while-following-tumblelog-application-with-flask-and-mongoengine

**Comment by serhatbolsu** [comment]
I am also having this problem, and it was major blocker for me, I hope this will be fixed in next release

**Comment by noirbizarre** [comment]
It's an upstream issue, fixed in MongoEngine/mongoengine#946
