### ISSUE TITLE
model_form: Field must be unbound, not a field class

### ISSUE THREAD

**Issue by Garito** [MongoEngine/flask-mongoengine#138]
I'm trying to use model_form with my models but when I try to call it with the request.form it raises the Field must be unbound

Could someone point me my mistake here, please

Thanks!

**Comment by Garito** [comment]
Seems that is mandatory to specify the list of fields
If I add the only param with the list of the fields I need to render it works

Is this correct?

Thanks

**Comment by lafrech** [comment]
Hard to answer without sample code. Please provide code and reopen if you are still interested.

**Comment by spitzbubchen** [comment]
I just ran across the same issue.

It seems that this occurs when model_form is used on a model containing ObjectIdField().

class Form(db.Document):
	parent = db.ObjectIdField()

**Comment by wojcikstefan** [comment]
Will be handled in #243
