### ISSUE TITLE
Non persistent field

### ISSUE THREAD

**Issue by Garito** [MongoEngine/flask-mongoengine#139]
Hi!
I'm trying to create a User's model to sign up, login, etc and I'm wondering how to define the password confirmation field in my model to generate the WTForm

Is there any kind of non persisten field of is there any model_form mechanism to do so?

Thanks!

**Comment by losintikfos** [comment]
I have pull request #147 - when merged you will be able to do:
```
class ChangePassword(db.Document):
    password = StringField(
         verbose_name='New Password', 
         validators=[
           validators.InputRequired(message='Password required'), 
           validators.EqualTo('confirm', message='Passwords must match')
         ]
     );
    confirm  = StringField(verbose_name='Repeat Password')
```

**Comment by Garito** [comment]
Sorry, I don't get it: how confirm is not persistent given the current definition?
Thanks!

**Comment by losintikfos** [comment]
Currently this is how close you can get to what you want to achieve.

My suggestion will be to remove confirm before saving:

```
if form.validate():
    form.populate_obj(some_obj)
			  
    # Remove confirm
    some_obj.confirm = None
    some_obj.save()
```

**Comment by Garito** [comment]
I understand

Thanks!
