### ISSUE TITLE
Unittest

### ISSUE THREAD

**Issue by Garito** [MongoEngine/flask-mongoengine#140]
Hi!
Can someone point me how to unittest model_form without create the whole Flask app?

I'm trying to test my model that has a function to generate the form with model_form and I would like to test it without testing the flask app

is it possible?

Thanks

**Comment by lafrech** [comment]
I'm not sure I understand the use case. The test framework in flask-mongoengine does instantiate a test flask app.

https://github.com/MongoEngine/flask-mongoengine/blob/master/tests/test_forms.py

Is this an issue?

Are you still interested in this issue?

**Comment by Garito** [comment]
Not interested anymore, sorry
