### ISSUE TITLE
MongoEnginge 0.9 deprecates snapshot field - Breaks Pagination

### ISSUE THREAD

**Issue by rturk** [MongoEngine/flask-mongoengine#141]
Breaks Flask-Mongoengine Pagination

https://github.com/MongoEngine/mongoengine/pull/946

**Comment by lafrech** [comment]
I'm using Pagination and it does not seem broken.

Is this fixed?

If not, can you please indicate how you reproduce the error?

**Comment by lafrech** [comment]
Please reopen if issue persists.
