### ISSUE TITLE
Is this project still maintained ?

### ISSUE THREAD

**Issue by noirbizarre** [MongoEngine/flask-mongoengine#143]
Hi !

I noticed that:
- there is a very low activity (compared to mongoengine)
- issues are not responded
- pull-request are neither merged nor commented
- th only milestone is outdated

Even if there is some (very low) activity, it does not follow mongoengine development (#941, #134).

So I'm wondering if this project is still maintain, and by whom ?
(It's not an attach or whatever, I only want to know if it's worth contributing)

**Comment by rozza** [comment]
Always looking for active maintainers - so ping me directly if interested @noirbizarre

**Comment by noirbizarre** [comment]
@rozza: I'm interested, but I'm not sure to be able to do it full time. I like the approach on mongoengine: many maintainers and a vote for merge.

**Comment by rozza** [comment]
@noirbizarre I'm sure any help is appreciated.  @itsnauman is currently doing some good work on the tickets - so he would be the person to reach out to about what to help on!

**Comment by Jerome-github** [comment]
Hi all.

An important commit has been merged that fixes compatibility with latest Mongoengine: https://github.com/MongoEngine/flask-mongoengine/commit/0922cb5fe10ccb93713f0d39df54c73e2aaf05e9.

Currently, using latest versions of Mongoengine and Flask-mongoengine from Pypi results in a broken setup (see [discussion on SO](http://stackoverflow.com/questions/34161163/python-wtf-attributeerror-objectidfield-object-has-no-attribute-help-text) for instance) and users have to hold their Mongoengine version.

It would be nice to release a 0.7.5 that includes this fix. I suggested this in a comment to the commit, but I don't know who got notified. Should I ping any of @rozza, @itsnauman or @losintikfos explicitly?

**Comment by lafrech** [comment]
Releasing a 0.7.5 would also add fix a pymongo3 issue (safe being removed) thanks to https://github.com/MongoEngine/flask-mongoengine/commit/f9c8c68ba8790bf479e68ae171db3ad6692b8453.

@rozza, where is the good place to discuss / get info about MongoEngine and flask-mongoengine roadmap? Github bugtracker? Mailing-list? IRC?

Mongoengine has about 250 issues open and 30 pull-requests. I can't do much about the pull requests, but I wouldn't mine helping to sort the issues (adding labels such as "question", "enhancement", "bug", "on hold" or"awaiting answer", "duplicate", etc.).

**Comment by genxstylez** [comment]
@lafrech agreed

**Comment by lafrech** [comment]
https://github.com/MongoEngine/flask-mongoengine/releases/tag/0.7.5

> - Changes to resolve MongoEngine deprecated attribute issues
> - Ensure issue with Pypy3 resolved
> - SESSION_TTL setting accepted via app config to ensure session timeout
to override default timeout of 1 day.
> - Provided RadioField component via model form
> - Other enhancements

Thank you, @losintikfos.

And thanks for highlighting [CONTRIBUTING.rst](https://github.com/MongoEngine/flask-mongoengine/blob/master/CONTRIBUTING.rst).

**Comment by losintikfos** [comment]
Version 0.7.5 is available.

**Comment by lafrech** [comment]
@noirbizarre, let's discuss involvement into the development in @rozza's [Call for Maintainers](https://github.com/MongoEngine/flask-mongoengine/issues/71)
