### ISSUE TITLE
Choices on model_form

### ISSUE THREAD

**Issue by Garito** [MongoEngine/flask-mongoengine#144]
Hi!
I'm trying to load a choices set for a field that it is in the context of the app so not created yet when the model is loaded

For me, the good solution for this will be, for instance, to allow model_form use choices as valid field attr but would like to ask before subclass the converter

How do you think we can solve this?

Thanks!

**Comment by losintikfos** [comment]
Have you tried importing your `choices set` directly in the document that need it. Example:

```
class Contact(db.Document):
    from countries_object_that_is_only_available_after_app_context import countries
    countries = db.StringField(required=True, choices=countries) 
```

**Comment by Garito** [comment]
Thanks
