### ISSUE TITLE
Canonical way to update a document with ImageFile

### ISSUE THREAD

**Issue by Garito** [MongoEngine/flask-mongoengine#149]
Hi!
I'm trying to update a document with and ImageFile but I can't find a way that it works

Or I end up with an error (the last one: InvalidDocument: Cannot encode object: <FileStorage: u'avatar pocoyo rostro.png' ('image/png')>) or I end up with a  <ImageGridFsProxy: (no file)> 

Could you point me how to do so?

Thanks!

**Comment by Garito** [comment]
Hi!
I need to solve this issue so I would ask a lot till I can move on

The think is if I go to mongo the images.files collection has the record of the image but the chunks in images.chunks are empty

Why is that? What I'm doing wrong?

Thanks!

**Comment by Garito** [comment]
Here is how I try to update my document:
http://pastebin.com/MfZMteUr

**Comment by lafrech** [comment]
Hard to answer without sample code. Please provide code and reopen if you are still interested.
