### ISSUE TITLE
Allow RadioField

### ISSUE THREAD

**Issue by Garito** [MongoEngine/flask-mongoengine#154]
Hi!
I would like to use a StringField with choices as, instead of a SelectField or MultiSelectField, RadioField
For that I modify the orm.py adding 2 lines of code
Instead of:
```python
if field.choices:
            kwargs['choices'] = field.choices

            if ftype in self.converters:
                kwargs["coerce"] = self.coerce(ftype)
            if kwargs.pop('multiple', False):
                return f.SelectMultipleField(**kwargs)
            return f.SelectField(**kwargs)
```
I have
```python
if field.choices:
            kwargs['choices'] = field.choices

            if ftype in self.converters:
                kwargs["coerce"] = self.coerce(ftype)
            if kwargs.pop('multiple', False):
                return f.SelectMultipleField(**kwargs)
            if kwargs.pop('radio', False):
                return f.RadioField(**kwargs)
            return f.SelectField(**kwargs)
```
Notice this 2 new lines:
```python
            if kwargs.pop('radio', False):
                return f.RadioField(**kwargs)
```
I would prefer to make a pull request but I wasn't able to run the test (if you could point me to the test help I would apreciate it)

In the other hand, I would prefer that choices will be treated in the converter to allow subclassing better but this change will be ok for me

What do you think?

Thanks!

**Comment by Garito** [comment]
Hello?

**Comment by rozza** [comment]
Sounds fine to me @itsnauman @noirbizarre any thoughts?

**Comment by Garito** [comment]
Well, to be honest I don't since it breaks the converter's pattern because I would prefer to treat choices in the converter not in the preconverter like now

But this solve my specifc problem right now

**Comment by noirbizarre** [comment]
Concept seems fine to me but without a pull-request wa can't see the whole picture.

To run the tests: ``python setup.py nosetests``

To run the tests on all Python versions and with different MongoEngine versions: ``tox``

I will submit a PR with the testing documention and an updated ``CONTRIBUTING.rst``.
(By the way, we should alos make tests pass on master: https://travis-ci.org/MongoEngine/flask-mongoengine/)

**Comment by Garito** [comment]
@noirbizarre sorry but your library is a mess right now because of the lack of update
If you run python setup.py nosetests you will end up with a mongo driver version 3 and your test will all fail
To make them pass you will need to uninstall it and install version 2.8 with the typical pip install pymongo==2.8
Besides that I'm trying to create a test case for my two modifications (I also added support for booleanfields)
Let me do this and push the pull request

**Comment by noirbizarre** [comment]
@Garito It's not my library, I'm a contributor trying to improve it. :)

The problem with PyMongo 3.0+ is a known upstream MongoEngine problem, already fixed and soon to be released: MongoEngine/mongoengine#946

With the PyMongo 2.8 workaround, is it working (and sufficient for you to perform your tests) ?

**Comment by Garito** [comment]
Yes, yes... thank you so much
Let me check if I can write the tests and I push the PR soon

**Comment by Garito** [comment]
I think I mix another change here: https://github.com/MongoEngine/flask-mongoengine/compare/master...Garito:master
Is there a way to make the pull request without the TTL stuff?

**Comment by losintikfos** [comment]
@Garito do you need this opened?

**Comment by Garito** [comment]
Everything seems to work as expected since 0.7.5
Thanks!
