### ISSUE TITLE
PyPi package is outdated

### ISSUE THREAD

**Issue by hai-ld** [MongoEngine/flask-mongoengine#158]
Hi,

Version 0.7.2 was released in May but PyPI package wasn't updated yet. Could you please upload the new version to PyPI?

Many thanks!

**Comment by JMSwag** [comment]
+!

**Comment by losintikfos** [comment]
@hai-ld Thanks for reporting this - looking into this.

**Comment by AlmogCohen** [comment]
+1!!!!!!
Oh my god, I just had so much troubles with the old version 0.7.1 regrading some python3 compatibility issues. Finished my pull request then saw that the problem was already fixed in 0.7.2

**Comment by losintikfos** [comment]
Latest version currently on PyPI. 

-Thanks

**Comment by AlmogCohen** [comment]
Your'e super awesome! The project is very responsive and I like it :) See my other pull request to fix the travis problems I made :)
