### ISSUE TITLE
Failing tests and non-updated TravisCI

### ISSUE THREAD

**Issue by AlmogCohen** [MongoEngine/flask-mongoengine#168]
Hi, just made pull request to fix some problems while running the tests.

Anyway, I see that the TravisCI configuration is not updated and that the project is not tested against mongoengine version 0.10.0.

Please fix it and accept my pull request since its TravisCI status is much better that the previous not-accepted pull request :)

**Comment by losintikfos** [comment]
@AlmogCohen we are aware of the Travis build issue and working to resolve this - please re-submit your change request.

**Comment by AlmogCohen** [comment]
Cool, I just added another pull request to update the travis configuration with python 3.5 and mongoengine 0.10.0.

My previous pull request (5 minutes ago) fix many bugs with the tests, maybe you can accept that too.

**Comment by losintikfos** [comment]
Thanks

**Comment by AlmogCohen** [comment]
Things are going fast here! :) Just added another pull request to make the README look much better

**Comment by losintikfos** [comment]
Thanks
