### ISSUE TITLE
object has no attribute 'help_text'

### ISSUE THREAD

**Issue by rijkstofberg** [MongoEngine/flask-mongoengine#187]
Good day, 

I am new to mongoengine and flask and have been playing with the stack.  At the moment I am stuck on the above error.  My confusion stems from the fact that 'mongoengine/base/fields.py' seems to indicate that the help_text is optional, but 'flask_mongoengine/wtf/orm.py' tries to access the attribute directly, assuming that it exists.  It would be probably be safer to get it like that other attributes in that method:
'description': getattr(field, 'help_text', '')
It seems 'flask_admin/contrib/mongoengine/form.py' makes the same assumptions about 'help_text'.
What am I missing here?  Should I commit a patch for these 2 issues?

Regards
Rijk

**Comment by rijkstofberg** [comment]
LOL! Nevermind, I see there is a pull request to fix this problem out already.

**Comment by rijkstofberg** [comment]
So is there any milestone set for merging in the fix yet?

**Comment by losintikfos** [comment]
Pull request has been merged.

-Thanks
