### ISSUE TITLE
mongomock connection error

### ISSUE THREAD

**Issue by brunobelarmino** [MongoEngine/flask-mongoengine#191]
I'm trying to test a flask application which use flask-mongoengine and when i put "mongomock://localhost" on "MONGODB_HOST" or "MONGODB_SETTINGS" setting i have experienced an error: pymongo.errors.InvalidURI: Invalid URI scheme: URI must begin with 'mongodb://'

It happens because flask-mongengine don't expect mongomock uri like raw mongoengine:

### flask-mongoengine _create_connection method:

    if "://" in conn.get('host', ''):
        uri_dict = uri_parser.parse_uri(conn['host'])
        conn['db'] = uri_dict['database']

### mongoengine register_connection method:

    conn_host = conn_settings['host']
    if conn_host.startswith('mongomock://'):
        conn_settings['is_mock'] = True
    elif '://' in conn_host:
        uri_dict = uri_parser.parse_uri(conn_host)

Any advice?

**Comment by lafrech** [comment]
I'm closing this a I believe this is addressed (or will be addressed) by https://github.com/MongoEngine/flask-mongoengine/issues/98. Please (accept my apologies and) reopen if I'm wrong.
