### ISSUE TITLE
MongoEngine extension not available when installed on Windows

### ISSUE THREAD

**Issue by hunt3ri** [MongoEngine/flask-mongoengine#194]
When I use pip to install flask-mongoengine on Windows, it does not add the extension to flask.ext so when I attempt to configure the application nothing is available, eg:

from flask.ext.mongoengine import MongoEngine

does not resolve.

Anyone got any ideas on what's going on here?

**Comment by losintikfos** [comment]
It looks like your project cannot find your python installed library path. 

Try setting Python path to include your library in your environment variables. [Setting environment variables](https://docs.python.org/2/using/windows.html#excursus-setting-environment-variables).

**Comment by hunt3ri** [comment]
I think I was being overly reliant on Pycharm code completion.  I've modified my import statement to use flask_mongoengine directly rather than using the flask.ext.mongoengine form and Pycharm seems happier.  The flask docs seem to indicate this is now the preferred approach

http://flask.pocoo.org/docs/0.10/extensiondev/#ext-import-transition

Happy to close this issue
