### ISSUE TITLE
sessions.py open_sessions and SID reuse

### ISSUE THREAD

**Issue by mkmoisen** [MongoEngine/flask-mongoengine#199]
I had a quick question regarding the open_sessions method in `MongoEngineSessionInterface`:

    def open_session(self, app, request):
        sid = request.cookies.get(app.session_cookie_name)
        if sid:
            stored_session = self.cls.objects(sid=sid).first()

            if stored_session:
                expiration = stored_session.expiration

                if not expiration.tzinfo:
                    expiration = expiration.replace(tzinfo=utc)

                if expiration > datetime.datetime.utcnow().replace(tzinfo=utc):
                    return MongoEngineSession(initial=stored_session.data, sid=stored_session.sid)

        return MongoEngineSession(sid=str(uuid.uuid4()))

It looks to me like the following is true:

If the stored session exists, but it it expired, a new session with a new SID will be created. The old stored session will continue to exist in the database, undeleted.

Is this supposed to be the case?

**Comment by lafrech** [comment]
Hi.

See the [collection creation](https://github.com/MongoEngine/flask-mongoengine/blob/master/flask_mongoengine/sessions.py#L39):

```python
        class DBSession(db.Document):
            sid = db.StringField(primary_key=True)
            data = db.DictField()
            expiration = db.DateTimeField()
            meta = {
                'allow_inheritance': False,
                'collection': collection,
                'indexes': [{'fields': ['expiration'],
                             'expireAfterSeconds': 60 * 60 * 24 * 7 * 31}]
            }
```

It uses a [TTL index](https://docs.mongodb.org/manual/tutorial/expire-data/) to delete an expired session after 31 days.

(This is my understanding. If you see it behaving otherwise, please reopen.)
