### ISSUE TITLE
Adding custom field attributes

### ISSUE THREAD

**Issue by macfire** [MongoEngine/flask-mongoengine#200]
How can custom attributes be added to a field in either the Model or View?

My current solution is to attach the attributes to the model_form Meta. It works, but is not ideal.
When in the Jinja2 template, it would convenient to have the custom attributes accessible directly on each field. In my current solution, I have to do a look up on the form meta.

``` python
class Tasks(Document):
    task = StringField()
    completed = BooleanField(default=False)


class TasksView(FlaskView):
    form = model_form(Tasks)

    def index(self)
         form =  self.form(request.form,
                                  meta={'fields':[
                                            {'id':'completed','width':20, 'height':20},
                                            {'id':'task','width':80,'color':'purple'}
                                        ]
                                  })
         # do other stuff here
        return render_template("my_template.html", form=form)
```

_Note  for context: 
 I'm using the form object to not only render a form, but also in rendering a javascript grid, and other structures where custom attributes defined in Model or View would be convenient to have._

**Comment by losintikfos** [comment]
MongoEngine document fields for example [StringField](http://docs.mongoengine.org/en/latest/apireference.html#mongoengine.fields.StringField) or other, accepts keyword arguments to be used as attributes. 

The keywords arguments expressed as:

> **kwargs –
> 
> (optional) Arbitrary indirection-free metadata for this field can be supplied as additional keyword arguments and accessed as attributes of the field. Must not conflict with any existing attributes. Common metadata includes verbose_name and help_text.

Example:

```
class Tasks(Document):
    task = StringField(width=20, height=20, id="completed")
    completed = BooleanField(default=False, color="purple")
```

**Comment by macfire** [comment]
@losintikfos Yes, I had read that in the MongoEngine docs and tried.

 I am confused why the following error occurs in /flask_mongoengine/wtf/base.py

```python
class Tasks(Document):
    task = StringField(custom_param="hello")

Error:
File "/venv/lib/python3.4/site-packages/flask_mongoengine/wtf/base.py", line 23, in __init__
    BaseField.__init__(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'custom_param' 
```

**Comment by macfire** [comment]
I found a solution which uses a widget constructor:   http://stackoverflow.com/a/32910249/1911075

If using a widget is the correct (preferred) method, than this issue can be close.
If there is another method which is "better", then an example would be appreciated.

Thanks.
