### ISSUE TITLE
Error in assigning field in the model initialization

### ISSUE THREAD

**Issue by luheeslo** [MongoEngine/flask-mongoengine#202]
Hi,

I set a User model defined below:

 
```
class User(db.Document):                                                         
    username = db.StringField(max_length=100, required=True)                     
    email = db.EmailField(max_length=64, required=True)                          
    password_hash = db.StringField(max_length=128, required=True)                
                                                                                 
    @property                                                                    
    def password(self):                                                          
        raise AttributeError('password is not a readable attribute')             
                                                                                 
    @password.setter                                                             
    def password(self, password):                                                
        self.password_hash = generate_password_hash(password)       
```
 

In tests cases, I initialize the model as follows:

```
def test_example(self):                                                 
        u = User(password='example')                                                    
        # ... 
```
When I run the tests, happens the following error: mongoengine.errors.FieldDoesNotExist: The field 'password' does not exist on the document 'User'

This is a bug?Or I'm doing something wrong?

**Comment by lafrech** [comment]
Generally speaking (even out of `flask-mongoengine`), I don't think you can do `Class(property='something')` if property is not an argument for `Class`'s `__init__` method, can you?

What if you do this?

```
def test_example(self):                                                 
        u = User()
        u.password = 'example'

```

**Comment by luheeslo** [comment]
Hello @lafrech,

In my other project, I'm using SQLAlchemy and it works. I solved this problem using your example, 
but I think the first approach is more practical in Python. But it is a mere detail.

Thank you for your attention.

**Comment by lafrech** [comment]
Oh, I didn't know it worked in any other ORM/ODM.

You may want to ask this as a feature request, and AFAIU, this would be in the MongoEngine project, not flask-mongoengine.

I think it happens [around here](https://github.com/MongoEngine/mongoengine/blob/master/mongoengine/base/document.py#L72) in MongoEngine.

**Comment by lafrech** [comment]
I'm closing this as I think it is a MongoEngine issue.

You may open the same issue in MongoEngine. However, since it is not a blocking one, I'm not sure it will be considered important, so don't expect too much of it.
