### ISSUE TITLE
WTForms: expose HTML5 fields

### ISSUE THREAD

**Issue by lafrech** [MongoEngine/flask-mongoengine#214]
WTForms added [fields to support various HTML5 input types](https://github.com/wtforms/wtforms/blob/master/wtforms/fields/html5.py).

It would be nice to expose these.

Currently, I suppose on can subclass `ModelConverter` to override some converters.

We could add support in flask-mongoengine code. Maybe using a kwarg in the model definition.

**Comment by lafrech** [comment]
On second thought, it should not be in the model definition. Maybe in `field_args`.

I'm wondering:

- Should this be specified for each field (can be painful), or could it be a form-wide parameter?

- Should HTML5 widgets be default? Would this break anything? I'd rather go the conservative way and not make it default, which is acceptable if it can be a form-wide parameter.

**Comment by lafrech** [comment]
Since old browsers [fallback on text input](http://stackoverflow.com/a/10521622) if they don't handle new type input, it is probably safe to use HTML5 inputs wherever possible.

For instance

- ME URLField -> WTF URLField -> WTF URLInput -> input type = "url"
- ME DecimalField -> WTF DecimalField -> WTF NumberInput -> input type = "number"

In this case, I don't see the need for a parameter to specify whether or not to use them: what regression could it cause?

It should be quite straightforward to use a majority if not all of those fields already.

There might be corner cases a bit tricky to address, though. For instance, the regex that validates a URL might not be the same as the one [specified in URLField](https://github.com/MongoEngine/mongoengine/blob/f420c9fb7c850b8269fa60747ea025b073171ce6/mongoengine/fields.py#L128).

**Comment by ripperdoc** [comment]
I made a local modification to use HTML5 from WTforms. Problem is for Datetime field. There are inconsistencies in browser support and seconds are not supported, while the underlying field does. So it is better to have it as a normal text-field or a custom date-picker. 

http://stackoverflow.com/questions/21263515/why-is-html5-input-type-datetime-removed-from-browsers-already-supporting-it

**Comment by lafrech** [comment]
Thanks for the feedback.

So you confirm that using HTML5 inputs by default won't harm (older browser will fallback to text input), so there's no need to make this optional, right?

In this case, I don't think anyone will object to adding this feature.

Do you have some code you would like to push here?

Let's add the easy ones already, and deal with the tricky ones like Datetime later on.

**Comment by ripperdoc** [comment]
Well, I haven't tested my code with many browsers, so cannot confirm no harm, but I give +1 for the idea.

**Comment by insspb** [comment]
Since WTForms 3.0.0 HTML5 is default.

**Comment by insspb** [comment]
I checked compatibility, and according tests nothing broke in #497 
So we are attached to WTForms >=3.0.0 since future 2.0.0 release, and will use/have HTML5 fields support.
