### ISSUE TITLE
Raise exception if mongo URI doesn't contain DB name

### ISSUE THREAD

**Issue by bkabrda** [MongoEngine/flask-mongoengine#217]
So this just ate ~2 hours of my life and although it's entirely my fault (the documentation does say "Note that database name from uri has priority over name."), I think it'd make sense to raise exception if no database name is provided in the URI.

If one doesn't provide database name in URI, one ends with a misleading error saying `TypeError: name must be an instance of basestring` somewhere in PyMongo. My proposal is to raise exception here [1] if `uri_dict['database']` is `None`. AFAICS flask-mongoengie doesn't provide any (official) API to (re)set the DB name and since it doesn't work properly without DB name, then this should be considered error and not allowed (e.g. by raising exception, as I propose).

If you think this is ok, I'll be glad to submit a PR.

[1] https://github.com/MongoEngine/flask-mongoengine/blob/ec5d86775f75efe842e11935a8d2709958d85ad5/flask_mongoengine/__init__.py#L94

**Comment by losintikfos** [comment]
Thanks @bkabrda this will be addressed in relation with #98. Can you please make pull request.
