### ISSUE TITLE
new mongomock commit breaks flask init

### ISSUE THREAD

**Issue by ntcong** [MongoEngine/flask-mongoengine#220]
This small code snippet won't work

```
from flask import Flask
from flask.ext.mongoengine import MongoEngine

app = Flask(__name__)
db = MongoEngine(app)
```

```
current_app.config['TESTING'] == True and....
> RuntimeError: working outside of application context
```

I think because on _create_connection we don't have a app context yet. Init_app should take an app and get config from it, instead of using local app context.
Adding a parameter to _create_connection should be enough so I can do a PR if it's acceptable.

**Comment by ntcong** [comment]
any update on this ?
There are two ways to solve this: either we pass flask's app instance to _create_connection, or we pass the "TESTING" config (or remove it).
I don't know what is "good" by standard of the project so I need some input so I can make a PR

**Comment by lafrech** [comment]
I stumbled upon this today as well.

AFAIU, @ntcong's diagnosis is correct.

Removing this line fixes it:

    current_app.config['TESTING'] == True and

@losintikfos, can you explain the need to test for this? I mean, if the host starts with `mongomock`, should we care about `TESTING` being in the settings? MongoEngine does not seem to care: https://github.com/MongoEngine/mongoengine/blob/master/mongoengine/connection.py#L61

If there is any reason to test this, then `init_app` may pass `app` to `_create_connection`.

@losintikfos, I know you're working on the connection part and you don't have much time for it. Should we 

- send a PR with the removal of the `app.config['TESTING']` test?
- send a PR with `app` being passed to `_create_connection`?
- wait until you're done with the whole thing?

Thanks.

**Comment by losintikfos** [comment]
@lafrech I will ensure `TESTING` is used appropriately in the enhancement.

Thanks.

**Comment by lafrech** [comment]
Hi @losintikfos. Congratulations for your work on the connection module.

I don't know if you're done with it or not, but just in case, I thought I'd let you know I just tried latest master version of flask-mongoengine on my project and I still have this issue.

It fails [here](https://github.com/MongoEngine/flask-mongoengine/blob/master/flask_mongoengine/connection.py#L100):

    is_test = current_app.config.get('TESTING', False)

**Comment by losintikfos** [comment]
@lafrech can you send me a test case to simulate here please.

Ta!

**Comment by ntcong** [comment]
I think my original test still didn't work
```
from flask import Flask
from flask.ext.mongoengine import MongoEngine

app = Flask(__name__)
db = MongoEngine(app)
```

It's still the same problem: you shouldn't use current_app when initialize an extension. The prefered way is passing an app instance

**Comment by losintikfos** [comment]
@ntcong I having a look into this.

Ta

**Comment by lafrech** [comment]
I trimmed down my use case to this:

```python
from flask import Flask
from flask_mongoengine import MongoEngine


class Config(object):
    SECRET_KEY = ("whatever")

    MONGODB_SETTINGS = {
        'db': 'db',
        'host': 'localhost',
        'port': 27017,
        'username': 'user',
        'password': 'pwd'
    }


me = MongoEngine()


def create_app(**kwargs):

    app = Flask(__name__, **kwargs)

    app.config.from_object(Config)

    me.init_app(app)

    return app

app = create_app()
```

I think this use case (app factory) is less common.

However, @ntcong's example is precisely the use case described [in the docs](https://flask-mongoengine.readthedocs.io/en/latest/#configuration), so I'm wondering which use case actually work.

Anyway, thanks @losintikfos for investigating.
