### ISSUE TITLE
Testing with multiple MongoDB server configurations

### ISSUE THREAD

**Issue by dylaan** [MongoEngine/flask-mongoengine#221]
I'm trying to use a factory pattern to test (with Flask-Testing) my application using two different mongod instances on different servers. One is for development, one is for production. 

    def create_app(config):
        app = Flask(__name__, instance_relative_config=True)
        app.config.from_object(config)
        from model import db
        db.init_app(app)

    return app

I'm finding that each subsequent test-case is reusing the first MongoClient and not being recreated with the new settings. Is this expected?

**Comment by losintikfos** [comment]
At the moment this is expected. It has been addressed at #98  for `0.8` release.

Thanks

**Comment by dylaan** [comment]
@losintikfos Thanks for your response.
I don't actually want to use MongoMock, I want to use a real (but not production) mongod instance for testing, in my test cases. I can provide more info if you like?

**Comment by losintikfos** [comment]
Try setting a list of connections with different alias for both test and production.

E.g.

```
app.config['MONGODB_SETTINGS'] = [
     {
        'db'      :  'prod-db'  ,
        'host'   :  'localhost',
        'port'    :  2122
         'alias'  :  'TEST'
   },
     {
        'db'      :  'test-db'  ,
        'host'   :  'localhost',
        'port'    :  21222
        'alias'   :  'PROD'
   },
]
```

**Comment by dylaan** [comment]
@losintikfos: I got it working with the context manager (switch_db), but I had to explicitly define default AND an alias for using it with switch_db, like this:

    MONGODB_SETTINGS = [
        {
            'host' : "mongodb://prod_host",
            'alias' : 'default'
        },
        {
            'host' : "mongodb://prod_host",
            'alias' : 'PROD'
        },
        {
            'host' : "mongodb://dev_host",
            'alias' : "TEST"
        }
    ]

After digging deeper, I'm convinced my problems are with mongoengine and not the flask extension specifically, so feel free to close I guess. Cheers!
