### ISSUE TITLE
change flask.ext to flask_ext

### ISSUE THREAD

**Issue by AlJohri** [MongoEngine/flask-mongoengine#222]
https://github.com/pallets/flask/issues/1135

```
from flask.ext.mongoengine import MongoEngine
```

should changed to

```
from flask_mongoengine import MongoEngine
```

throughout the codebase.

Getting `ExtDeprecationWarning` on master branch of Flask.

Currently using this:

```
from flask.exthook import ExtDeprecationWarning
import warnings
warnings.simplefilter("ignore", category=ExtDeprecationWarning)
from flask_mongoengine import MongoEngine
```

**Comment by trekkadmin** [comment]
I am using Flask 0.11.1 and  Flask-Mongoengine 0.7.10 with Python 2.7 in a virtualenv in Ubuntu 15.10 and still see the deprecation warning.  For example:

```python
/env_route/re_virtual/local/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.mongoengine is deprecated, use flask_mongoengine instead.

```

After using the warning suppression technique above this issue goes away.

**Comment by lafrech** [comment]
The fix is [merged in master](https://github.com/MongoEngine/flask-mongoengine/pull/223) and will be available in next flask-mongoengine version, which should be 0.8.0.

Most likely, you're using 0.7.5 (latest), not 0.7.10, which does not exist.

**Comment by trekkadmin** [comment]
@lafrech, ah, thank you very much.  I will watch for the update.  Appreciate it.

**Comment by glifchits** [comment]
@lafrech any idea when 0.8.0 will be published? I've been watching the project since that fix was merged, which was quite a while ago at this point.

**Comment by lafrech** [comment]
I can't provide any time estimation.

Only one feature is holding the release: the [rework of connection to allow mongomock testing](https://github.com/MongoEngine/flask-mongoengine/issues/98). Current implementation has [one known bug](https://github.com/MongoEngine/flask-mongoengine/issues/220).

https://github.com/MongoEngine/flask-mongoengine/milestones/0.8

**Comment by losintikfos** [comment]
@lafrech #220 has been resolved and issue closed. `0.8.0` release is due later this week.

Ta!

**Comment by trekkadmin** [comment]
@losintikfos Excellent!  Thanks.

**Comment by lafrech** [comment]
Great, @losintikfos. I didn't see that: I only get notified for issue comments, not for commits pushed to the repo.
