### ISSUE TITLE
7.5 MONGODB_SETTINGS not compatible in 8.0

### ISSUE THREAD

**Issue by denny0223** [MongoEngine/flask-mongoengine#235]
My app load DB config from `app.config["MONGODB_SETTINGS"]`, the settings data is
```
{'USERNAME': None, 'HOST': 'localhost:27017', 'PASSWORD': None, 'DB': 'my_db'}
```

It's working for me in 7.5, but in current master(abe18d58068c99d36ee9693b5b33f94c85efe421) it's not work, because of in fce79d8adaac528bca4c7301f4a5e36a40d7e0e4 it change to load setting from the key with `MONGODB_` prefix, [more detail](https://github.com/MongoEngine/flask-mongoengine/commit/fce79d8adaac528bca4c7301f4a5e36a40d7e0e4#diff-6f4e01df5cd20afc19d221256724b7fcR249).

But I haven't seen any thing about this in changelog.

**Comment by losintikfos** [comment]
@denny0223 thanks for reporting this - I will refactor the handler to ensure this is resolved.

Ta!

**Comment by losintikfos** [comment]
@denny0223  did master(af2e6baab3ffebe66aa6ff9d9723e96c08794334) resolve your issue?

**Comment by denny0223** [comment]
Yes, it's work! Thanks!
