### ISSUE TITLE
Potentiel regression in connection handling

### ISSUE THREAD

**Issue by lafrech** [MongoEngine/flask-mongoengine#241]
I have a script that used to work with former versions of flask-mongoengine and doesn't with latest master.

It is possible that the use case is twisted and it should not have worked in the first place.

In order to test my Flask app, I wrote a script to fill a database with random data. To simplify the process, I'm reusing the model defined in the application to create the data.

So I use MongoEngine to connect to the DB, with `Document`s that inherit from flask-mongoengine's MongoEngine.

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import mongoengine as me

# Document imported from application
# inherits from flask_mongoengine's MongoEngine
from flask_mongoengine import MongoEngine
db = MongoEngine()

class User(db.Document):

    name = me.StringField()


# Flask-style config imported from Flask's setting.py file
class Config(object):
    MONGODB_SETTINGS = {
        'alias': 'default',
        'db': 'testrtksdfdsf',
        'host': 'localhost',
        'port': 27017,
    }


# Data generator
def fill_db():
    """Fill database with random data"""

    # Connect using MongoEngine
    # no Flask app created
    db_config = Config.MONGODB_SETTINGS
    connection = me.connect(**db_config)
    # Workaround for https://github.com/MongoEngine/mongoengine/issues/851
    me.connection.get_db()
    connection.drop_database(db_config['db'])

    # Create a lot of random data
    User(name='Name').save()

    me.connection.disconnect()

if __name__ == "__main__":

    fill_db()
```

This used to work but now fails with:

    mongoengine.connection.ConnectionError: Connection with alias "default-mongodb-connection" has not been defined

I got it to work by replacing `default-mongodb-connection` in flask-mongoengine code with `default` which is the value from MongoEngine. I have no idea whether this is the right thing to do or whether I should be doing things a totally different way.

In any case, I wouldn't copy the value, but rather import it from `mongoengine.connection`, so it could look like this:

```python3
from mongoengine import connection

DEFAULT_CONNECTION_NAME = mongoengine.connection.DEFAULT_CONNECTION_NAME
```

I hope I'm making sense.

**Comment by lafrech** [comment]
@losintikfos, does the "fix" I propose make sense?

```py
from mongoengine import connection
DEFAULT_CONNECTION_NAME = mongoengine.connection.DEFAULT_CONNECTION_NAME
```

Any reason to have a 'default' different from MongoEngine's?

**Comment by losintikfos** [comment]
@lafrech sorry for the break in response - busy as usual. Please note connection to `MongoDB` via `MongoEngine` is proxied via `flaskMongoEngne` .

Therefore bypassing your applications instance connection to initiate connection direct via `MongoEngine` such as:

```py
    connection = me.connect(**db_config)
    me.connection.get_db()
```
 will result to the error reported.

I will kindly suggest that - if you want an active instance of MongoEngine from your working application then you use:

```py
from flask_mongoengine import current_mongoengine_instance
me = current_mongoengine_instance()
if me_instance:
    connection = me.connection
    ...
```
Alternatively you can do something like this:
```py
db = MongoEngine()
..
db.init_app(app)
connection  = db.connection
```

Hope this helps.

**Comment by lafrech** [comment]
Hi. Thanks for answering.

The point is I'm not starting an `app` at all. I'm just reusing the flask-mongoengine model defined in the `app` to help me fill the database with random data. `current_app` is never defined. I'm connecting with MongoEngine and using my flask-mongoengine model as if it was a ME Model.

This might not be a supported use case. It just happened to work on former flask-mongoengine versions. And it also happens to work if I set `DEFAULT_CONNECTION_NAME` to the same value as in MongoEngine, but maybe it's just "luck" and it shouldn't be relied upon.

You may ignore (close) this issue if you think this is not in the scope of flask-mongoengine.

Or if you don't mind, change the value of `DEFAULT_CONNECTION_NAME` but maybe that would just allow me to maintain a feature that is unsupported so bound to break...

Anyway, apart from this, I didn't see any issue that would block 0.8.

**Comment by sebastiancodes** [comment]
I think the "proper" way to do this, is by using the [application context](http://flask.pocoo.org/docs/0.11/appcontext/#creating-an-application-context).

```
def create_app(config_name="testing"):
    app = Flask('my_app')
    app.config.from_object('app.config.default')
    app.config.from_object('app.config.{}'.format(config_name))

def fill_db():
    app = create_app('testing')
    with app.app_context():
        User(name='Name').save()
```

**Comment by losintikfos** [comment]
@lafrech Mixing `FlaskMongoEngine` instance with direct `MongoEngine` connection will produce the error reported. The connection handler enhancement ensures all calls to `MongoEngine` connection is proxied via the new FlaskMongoEngine connection module.

To avoid this error - ensure:

1. No call to ` MongoEngine` class is instantiated anywhere in your application - which will cause the proxying to take effect. i.e.
```py
   
    from flask_mongoengine import MongoEngine
    db = MongoEngine()
    ...
```

With that in mind a direct connection via `mongoengine` in your approach should now look something like this:

```py
    import mongoengine as me

    class User(me.Document):
        name = me.StringField()

    # Flask-style config imported from Flask's setting.py file
    class Config(object):
        MONGODB_SETTINGS = {
            'alias': 'default',
            'db': 'testrtksdfdsf',
            'host': 'localhost',
            'port': 27017,
        }

    # no Flask app created
    db_config = Config.MONGODB_SETTINGS
    connection = me.connect(**db_config)

    me.connection.get_db()
    connection.drop_database(db_config['db'])

    # Create a lot of random data
    User(name='Name').save()
    me.connection.disconnect()
```

You are right, I don't think this should block `0.8` release - therefore I am going to close this.

Ta!
