### ISSUE TITLE
Mongomock support on release ...?

### ISSUE THREAD

**Issue by ilmesi** [MongoEngine/flask-mongoengine#242]
Great repo guys.

I'm really interested on the mongomock support on master. But:
- Can't see anything about it on release 0.7.5
- 0.8.0 (which is not pushed) changelog does not mention it

Does it belong to a different milestone? When would be available?

Cheers,
Nacho

**Comment by lafrech** [comment]
It's almost done and it is actually the last feature holding 0.8.0 release.

**Comment by ilmesi** [comment]
Awesome, thanks for the quick answer!
