### ISSUE TITLE
model_form input labels not being capitalized

### ISSUE THREAD

**Issue by spitzbubchen** [MongoEngine/flask-mongoengine#244]
Maybe this is not specific to flask-mongoenine, but after pip upgrading a few packages (including this one) I noticed that all my form labels (created with `flask_mongoengine.wtf import model_form` and expressed as `{{ form.author.label }}` in my HTML) went from the first letter being auto capitalized to all letters being lower case. For example 'Author' went to 'author'. Kind of annoying, as all my website forms have now changed...

**Comment by lafrech** [comment]
To confirm this is due to flask-mongoengine, you may install former version and see what happens.

    pip install flask-mongoengine==0.7.5

**Comment by spitzbubchen** [comment]
When I reported the issue I was running flask-mongoengine==0.7.5. Just upgraded to flask-mongoengine==0.8 and this still occurs.

I will close this since my mongoengine model attributes are written in lowercase and the WTForms `.label` is just faithfully expressing this.

**Comment by lafrech** [comment]
Try to add a `verbose_name` attribute to your fields. IIRC, this attribute is set as label on form fields (this happens [here](https://github.com/MongoEngine/flask-mongoengine/blob/5143083581c778aa7aeb6fcbd925ac1697feb5c2/flask_mongoengine/wtf/orm.py#L46)).

            class Example(db.Document):
                test = db.StringField(verbose_name='Test')

**Comment by spitzbubchen** [comment]
Cool! That did the trick.
