### ISSUE TITLE
Connecting to multiple databases is not working

### ISSUE THREAD

**Issue by sebastiancodes** [MongoEngine/flask-mongoengine#246]
My app loads the configuration from app.config["MONGODB_SETTINGS"] and I use this to connect to multiple databases, as supported by mongoengine since version 0.6 (http://docs.mongoengine.org/guide/connecting.html#multiple-databases)

The configuration data is like this:
[
    {"ALIAS": "default", "DB": 'my_db1', "HOST": 'localhost', "PORT": 27017},
    {"ALIAS": "my_db2", "DB": 'my_db2', "HOST": 'localhost', "PORT": 27017},
]

It's working for me in 7.5, but it's not working in the current master.

**Comment by losintikfos** [comment]
@sebastiancodes Try something like this:

```py
...

def test_multiple_connections(self):
    db = MongoEngine()
    self.app.config['TESTING'] = True
    self.app.config['MONGODB_SETTINGS'] = [
        {
         "ALIAS": "default",
         "DB":    'my_db1',
         "HOST": 'localhost',
         "PORT": 27017
        },
        {
         "ALIAS": "my_db2",
         "DB": 'my_db2',
         "HOST": 'localhost',
         "PORT": 27017
        },
    ]
    class Todo(db.Document):
        title = db.StringField(max_length=60)
        text = db.StringField()
        done = db.BooleanField(default=False)
        meta = {"db_alias": "my_db2"}

    db.init_app(self.app)
    Todo.drop_collection()

    # Switch DB
    from mongoengine.context_managers import switch_db
    with switch_db(Todo, 'default') as Todo:
        todo = Todo()
        todo.text = "Sample"
        todo.title = "Testing"
        todo.done = True
        s_todo = todo.save()

        f_to = Todo.objects().first()
        self.assertEqual(s_todo.title, f_to.title)
```

**Comment by sebastiancodes** [comment]
@losintikfos Hi, thanks for your reply, but I think you've misunderstood the issue. I'm not trying to switch between DB's. I'm just trying to connect to [multiple databases].(http://docs.mongoengine.org/guide/connecting.html#multiple-databases)

However, I think the actual issue is that flask-mongoengine is using "default-mongodb-connection" as default connection name, instead of 'default' which is used by MongoEngine.

Is there any reason why flask-mongoengine has a different 'default' different then MongoEngine?

**Comment by losintikfos** [comment]
@sebastiancodes try pull the latest master changes committed this afternoon - I believe it should resolve your issue. 

Thanks

**Comment by sebastiancodes** [comment]
@losintikfos Okay, I will. Thank you very much!

**Comment by losintikfos** [comment]
Will close this until further response.

Thanks
