### ISSUE TITLE
Сan not connect to the database with login and password

### ISSUE THREAD

**Issue by asduj** [MongoEngine/flask-mongoengine#248]
When initializing the application **does not register a new connection** with credentials from MONGODB_SETTINGS. Because of this, the following is obtained:

1) in get_connection in 141 called mongoengine.connect without credentials (101-104)
2) in mongoengine.connect without credentials called register_connection
3) in register_connection updated **global** _connection_settings and in fact delete credentials

That is all. And you get an error that can not connect to the database because you are not authenticated.

**Comment by losintikfos** [comment]
Fix merged.
