### ISSUE TITLE
authentication failed by "authentication_source" is missing

### ISSUE THREAD

**Issue by luoqiwen** [MongoEngine/flask-mongoengine#256]
here is my local fixing...

diff --git a/flask_mongoengine/connection.py b/flask_mongoengine/connection.py
index 31a0de9..9b3cde4 100644
--- a/flask_mongoengine/connection.py
+++ b/flask_mongoengine/connection.py
@@ -251,6 +251,7 @@ def _resolve_settings(conn_setting, removePass=True):
         port = conn_setting.get('port', 27017)
         username = conn_setting.get('username', None)
         password = conn_setting.get('password', None)
`+        authentication_source = conn_setting.get('authentication_source', 'admin')`
         # Default to ReadPreference.PRIMARY if no read_preference is supplied
         read_preference = conn_setting.get('read_preference', ReadPreference.PRIMARY)

@@ -262,6 +263,7 @@ def _resolve_settings(conn_setting, removePass=True):
         resolved['password'] = password
         resolved['port'] = port
         resolved['username'] = username
`+        resolved['authentication_source'] = authentication_source`
         replica_set = conn_setting.pop('replicaset', None)
         if replica_set:
             resolved['replicaSet'] = replica_set

**Comment by losintikfos** [comment]
Please can you make a pull request for your fix together with a test coverage in `tests.test_connection.py`?

Ta!

**Comment by ntcong** [comment]
per #250, there're some cases where people want to set a configuration for mongoengine, like with tz_aware, or in this case authentication_source.

Should we explicit set each and every one of them and potentially missing something, or we passed down all of the custom setting to mongoengine?

**Comment by lafrech** [comment]
Contributors willing to fix the connexion regression in 0.8 are welcome to join in https://github.com/MongoEngine/flask-mongoengine/issues/71#issuecomment-252554167.

**Comment by wojcikstefan** [comment]
Should be fixed in v0.8.1, v0.8.2, and v0.9.0.
