### ISSUE TITLE
GridFS support not working in 0.8

### ISSUE THREAD

**Issue by spitzbubchen** [MongoEngine/flask-mongoengine#257]
After upgrading to 0.8 I am running into issues with GridFS support. For example, I have a model:

```
class User(db.Document, UserMixin):
    image = db.ImageField()
```

Now if I do:

```
user = User.objects.get_or_404(id = id)
image = user.image.read()       
temp = BytesIO()
temp.write(image)
```

I get the following error:

`TypeError: 'NoneType' does not support the buffer interface`

Downgrading to 0.7.5 things work as expected.

**Comment by wojcikstefan** [comment]
@spitzbubchen could you check if it's still an issue with v0.9.0?

**Comment by spitzbubchen** [comment]
Upgraded to flask-mongoengine==0.8.2. Happy to report that things are working :+1:

**Comment by lafrech** [comment]
Let's close this, then. Thanks for the feedback.
