### ISSUE TITLE
Comparing ReferenceField to None still does db query?

### ISSUE THREAD

**Issue by ScriptProdigy** [MongoEngine/flask-mongoengine#262]
In a clean() method of a document model I have I'm checking if a referencefield of that document is None. It appears that its doing a db query because of how long it takes to compare to none.

```
class Owner(Document):
    child = ReferenceField(someotherdoc)
    other = StringField()

    def clean(self):
        if self.other is None: # Takes almost 0 time, as expected (~0.0002 seconds alone)
            self.other = SomeLogicHere
        if self.child is None: # this takes exponentially more time. (~.002 seconds alone) 
            self.child = SomeLogicHere
```

Anyone know how to properly check if the document has it without forcing a db query? Or whatever it's actually doing. The object is already in memory obviously, I tried hasattr as well but this seems to be executing the same logic that is making the above slow.

And tips and suggestions are appreciated. That .002 seconds adds up quickly, only 1k items is 2 seconds alone..

Keep in mind, everything I'm doing currently is in a local development setup and has not been tested in a production environment yet.

**Comment by lafrech** [comment]
I'm pretty sure this is a MongoEngine issue, unrelated to flask-mongoengine.

Would you mind opening the issue [there](https://github.com/MongoEngine/mongoengine/issues)?
