### ISSUE TITLE
Changing settings for unit tests

### ISSUE THREAD

**Issue by quantoid** [MongoEngine/flask-mongoengine#264]
The documentation really needs a brief section explaining how to inject different settings into the MongoEngine constructor for unit tests.

This package looks like it adds a bunch of good stuff on top of mongoengine for use in Flask apps, so I really want to use it, but I'm having trouble working out how to set things up for unit tests, which is a blocker if you're doing test-driven development. 

Say you have a main module something like this:

```
app = Flask(__name__)
app.config.from_object(settings)
ddb = MongoEngine(app)
...
```

and unit tests like this:

```
from myapp.main import app

class APIAcceptanceTests(TestCase):
    def setup(self):
        self.client = app.test_client()

    def test_fruits(self):
         """API returns list of fruits"""
        reply = self.client.get('/api/fruits')
        self.assertEqual(200, response.status_code)
```

The trouble here is that the `MongoEngine` wrapper has already been created when you import `app`. That constructor calls `create_connection` which has special test-friendly behaviour when the app is configured in testing mode, so in unit tests you really want to change the configuration _before_ calling it.

What's the neatest way to inject different settings from unit tests so the `MongoEngine` wrapper gets those?

**Comment by quantoid** [comment]
I did consider doing this but it seems clunky and I'm not sure it's future-safe:

    from myapp.main import app, ddb

    class APIAcceptanceTests(TestCase):
        def setup(self):
            app.config.update({
                "TESTING": True,
                "TEMP_DB": True,
            }
            # Reinitialise database with new settings.
            ddb.init_app(app)
            self.app = app.test_client()

**Comment by quantoid** [comment]
I've tried doing a separate initialisation with test-specific settings that include `TEMP_DB=True` like this:

    app = Flask(__name__)
    app.config.from_pyfile("test_settings.py")
    ddb = MongoEngine(app)
    api = register_api(app)

This throws an exception because `/bin/sh` can't find `mongod` even though it can when I use it directly in a shell:

    RuntimeError: You need `MongoDB` service installed on localhost to create a TEMP_DB instance.

If I hack `_register_test_connection` to run `/usr/local/bin/mongod` I get an application context exception:
```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/Users/mhowells/env/gnizer/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/mhowells/env/gnizer/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/mhowells/env/gnizer/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/mhowells/workspace/gnizer/gnizer/tests/__init__.py", line 16, in <module>
    ddb = MongoEngine(app)
  File "/Users/mhowells/env/gnizer/lib/python2.7/site-packages/flask_mongoengine/__init__.py", line 111, in __init__
    self.init_app(app, config)
  File "/Users/mhowells/env/gnizer/lib/python2.7/site-packages/flask_mongoengine/__init__.py", line 138, in init_app
    connection = create_connection(config, app)
  File "/Users/mhowells/env/gnizer/lib/python2.7/site-packages/flask_mongoengine/connection.py", line 377, in create_connection
    return get_connection(alias)
  File "/Users/mhowells/env/gnizer/lib/python2.7/site-packages/flask_mongoengine/connection.py", line 120, in get_connection
    return _register_test_connection(port, db_alias, preserved)
  File "/Users/mhowells/env/gnizer/lib/python2.7/site-packages/flask_mongoengine/connection.py", line 210, in _register_test_connection
    _tmpdir = current_app.config.get('TEMP_DB_LOC', tempfile.mkdtemp())
  File "/Users/mhowells/env/gnizer/lib/python2.7/site-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/mhowells/env/gnizer/lib/python2.7/site-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/Users/mhowells/env/gnizer/lib/python2.7/site-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.
This typically means that you attempted to use functionality that needed
to interface with the current application object in a way.  To solve
this set up an application context with app.app_context().  See the
documentation for more information.
```
This doesn't make sense because it happens when constructing the MongoEngine wrapper, and similar code works fine outside the tests.

**Comment by jcass77** [comment]
I'm not sure that I fully understand what you are aiming for here so this might not be helpful: I use the [approach](https://github.com/sloria/cookiecutter-flask/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/settings.py) suggested by Flask-Cookiecutter  for configuring different settings for develop, testing, and production modes.

I haven't tried using a ``TEMP_DB`` yet seeing as [mongomock](https://github.com/mongomock/mongomock) has so far been able to provide everything that I need for creating unit tests.

**Comment by wojcikstefan** [comment]
> This throws an exception because /bin/sh can't find mongod even though it can when I use it directly in a shell

That's a Flask-MongoEngine issue related to a very buggy connection code in v0.8 (you can see my criticism at https://github.com/MongoEngine/flask-mongoengine/pull/231#issuecomment-255568259 and an upcoming fix in https://github.com/MongoEngine/flask-mongoengine/pull/280).

As for the original high-level question, you should be able to easily re-structure your code so that it supports initializing the `Flask` application depending on the environment (as @jcass77 pointed out). Then in unit tests you can call `setup_app('path.to.testing.config')` and in a place when you start your dev/prod server you can do `setup_app('path.to.dev.or.prod.config')`.

I'll close it for now - let me know if you need more assistance!
