### ISSUE TITLE
Warning: flask_wtf.Form has been renamed to "FlaskForm"

### ISSUE THREAD

**Issue by aiden0z** [MongoEngine/flask-mongoengine#265]
flask_mongoengine/wtf/models.py:3: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.

**Comment by lafrech** [comment]
Thanks for pointing this out.

Would you care to send a PR?

From a quick look, it could be only [wtf/models.py](https://github.com/MongoEngine/flask-mongoengine/blob/f8c3bc839b72b9a438949cd629bc64adee313c8d/flask_mongoengine/wtf/models.py) to modify (plus setup.py to bump dependency on flask-wtf to >= 0.13).
