### ISSUE TITLE
WTForms shouldn't be imported if not used

### ISSUE THREAD

**Issue by thomasst** [MongoEngine/flask-mongoengine#267]
While I understand that flask-mongoengine provides specific support for WTForms, it should only attempt to import WTForms if we actually use the `flask_mongoengine.wtf` module. That way projects that don't need WTForms won't have to include and import that library. Currently, `.wtf` is imported in `__init__.py`, and is used in `MongoEngine.__init__` which calls `_patch_base_field`. This wasn't an issue prior to version 0.8 (https://github.com/MongoEngine/flask-mongoengine/commit/0982432ac83e80da575fd0090d1e5b1a417ca07b).

Can we do the patching somewhere else / only when importing the `.wtf` module explicitly?

**Comment by lafrech** [comment]
Good point. PR welcome.

[setup.py](https://github.com/MongoEngine/flask-mongoengine/blob/master/setup.py#L52) should be updated accordingly to make wtforms optional requirement.

**Comment by wojcikstefan** [comment]
https://github.com/MongoEngine/flask-mongoengine/pull/280 removes the hacky `_patch_base_field` and should thus fix this issue.

**Comment by lafrech** [comment]
Is this solved?

**Comment by wojcikstefan** [comment]
Not yet, unfortunately (edited my last comment)

**Comment by insspb** [comment]
Finally this is done and available in master.
