### ISSUE TITLE
Regression in the tests with Flask-WTF>=0.13

### ISSUE THREAD

**Issue by lafrech** [MongoEngine/flask-mongoengine#269]
I manually [relaunched a test](https://travis-ci.org/MongoEngine/flask-mongoengine/jobs/156143238) to try the new Flask-WTF release and it breaks in [test_modelselectfield_multiple](https://github.com/MongoEngine/flask-mongoengine/blob/master/tests/test_forms.py#L307).

```
======================================================================
1) FAIL: test_modelselectfield_multiple (tests.test_forms.WTFormsAppTestCase)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/test_forms.py line 307 in test_modelselectfield_multiple
      self.assertEqual(form.dogs.data, None)
   AssertionError: [<Dog: Dog object>, <Dog: Dog object>] != None
       '[<Dog: Dog object>, <Dog: Dog object>] != None' = '%s != %s' % _common_shorten_repr([<Dog: Dog object>, <Dog: Dog object>], None)
       '[<Dog: Dog object>, <Dog: Dog object>] != None' = self._formatMessage('[<Dog: Dog object>, <Dog: Dog object>] != None', '[<Dog: Dog object>, <Dog: Dog object>] != None')
   >>  raise self.failureException('[<Dog: Dog object>, <Dog: Dog object>] != None')
```

I guess something changed in Flask-WTF that breaks the test.

**Comment by jtharpla** [comment]
This appears to be caused by this change in Werkzeug 0.11.11: https://github.com/pallets/werkzeug/pull/991 (fix multidict behavior for empty lists)

If I switch my local venv to Werkzeug==0.11.10, the failing test passes.
