### ISSUE TITLE
Travis build error

### ISSUE THREAD

**Issue by wojcikstefan** [MongoEngine/flask-mongoengine#278]
https://travis-ci.org/MongoEngine/flask-mongoengine

<img width="550" alt="screen shot 2016-11-05 at 5 10 52 pm" src="https://cloud.githubusercontent.com/assets/1718372/20033606/d67febe4-a37a-11e6-9e12-ceecea4ddcc8.png">

@lafrech unfortunately I'm not an admin in this repo, so I can't activate it. Could you please help?

**Comment by lafrech** [comment]
I'm not sure what the problem is. The tests seem to run.

I do get the same message and I get an error when clicking "activate repository" as I don't have admin rights here either (only on Mongoengine).

**Comment by wojcikstefan** [comment]
@MongoEngine/flask-mongoengine is there anybody with admin rights who can look into it? :)

**Comment by lafrech** [comment]
Cliked on the button.

Got error "There was an error while trying to activate the repository."

Not this today to investigate this. Sorry.

**Comment by wojcikstefan** [comment]
Ok, I managed to activate it. It still shows "error" because of the PyPy3 issues, but that should go away as soon as Flask v0.11.2 is released (because of https://github.com/pallets/flask/commit/6e46d0cd3969f6c13ff61c95c81a975192232fed).
