### ISSUE TITLE
Does the 0.8.1 bug-fixed version release date determined?

### ISSUE THREAD

**Issue by Folyd** [MongoEngine/flask-mongoengine#283]
I think the v0.8 is buggly, i can't image why the bug-fixed version still not released yet.

**Comment by denny0223** [comment]
#251 I had tried e300e77 in our beta server.

Maybe @wojcikstefan or @lafrech will release a new version to fix some critical bug in a few days.

**Comment by wojcikstefan** [comment]
I agree 100% that v0.8 is buggy and I'm sorry it's been taking longer than expected to get a fix released. Have you tried running your server with the latest commit from #280 by any chance?

**Comment by denny0223** [comment]
@wojcikstefan I had tried #280 in my server, it works fine.

**Comment by wojcikstefan** [comment]
Great, thanks @denny0223! I'll test out remaining scenarios from #280 (in the description) and merge if everything works well.

**Comment by TomIsPrettyCool** [comment]
Can confirm, v0.8.1 fixed all my connection and authentication issues,

**Comment by lafrech** [comment]
Thanks for the feedback.

A PyPi release should come soon: https://github.com/MongoEngine/flask-mongoengine/issues/71#issuecomment-264830237.
