### ISSUE TITLE
Add max_length feature to StringField-like fields

### ISSUE THREAD

**Issue by lafrech** [MongoEngine/flask-mongoengine#293]
Use max_length parameter so that generated HTML input has a maxlength attribute.

What I tried to do in https://github.com/MongoEngine/flask-mongoengine/pull/216... but better.

**Comment by insspb** [comment]
Seems outdated. 

Current generator, that uses WTForms 3.0.0 output this to fields definition.

If field defined as: 

```python
class StringsDemoModel(db.Document):
    """Documentation example model."""

    string_field = db.StringField(max_length=10)
```

Then HTML will be: 

```html
<input id="string_field" maxlength="10" name="string_field" style="font-weight: bold" type="text" value="">
```

My comments related/checked in current master with flsk-mongoengine 2.0.0+

Closing.

**Comment by insspb** [comment]
P.S. Related to deploy of #497
