### ISSUE TITLE
Broken with Flask-WTF v0.14.x

### ISSUE THREAD

**Issue by logsoft** [MongoEngine/flask-mongoengine#294]
happened in working code after flask pip upgrade.

setup: (only related)
Flask (0.12)
Flask-Admin (1.4.2)
Flask-DebugToolbar (0.10.0)
Flask-Login (0.4.0)
Flask-Markdown (0.3)
flask-mongoengine (0.8.2)
Flask-WTF (0.14.2)
itsdangerous (0.24)
Jinja2 (2.9.4)
mongoengine (0.11.0)
pymongo (3.4.0)
Werkzeug (0.11.15)
WTForms (2.1)

```
File "..../blog/views.py", line 34, in get_context
    form = self.form(request.form)
File "..../local/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
File "..../local/lib/python2.7/site-packages/flask_mongoengine/wtf/models.py", line 12, in __init__
    super(ModelForm, self).__init__(formdata, obj, **kwargs)
TypeError: __init__() takes at most 2 arguments (3 given)
```

changing line 12 in flask_mongoengine/wtf/models.py  from
```
        super(ModelForm, self).__init__(formdata, obj, **kwargs)
```
to:
```
        super(ModelForm, self).__init__(formdata, **kwargs)
```
solves the problem.
But i dont really know if this is the solution or just masking an error of my app.

**Comment by lafrech** [comment]
Thanks for reporting. I had a quick look. There's been important changes in Flask-WTForms recently. See [this commit](https://github.com/lepture/flask-wtf/commit/42befd0420d1f4896a70339de3d474044461a1c9), which is released in [v0.14](https://flask-wtf.readthedocs.io/en/stable/changelog.html#version-0-14).

I just relaunched the tests for latest flask-mongoengine commit and they fail: https://travis-ci.org/MongoEngine/flask-mongoengine/builds/187515401

I'd say stick to Flask-WTF v0.13.x until flask-mongoengine is fixed for v0.14 (help welcome).

**Comment by wojcikstefan** [comment]
@lafrech did you reran the tests on the master branch? The badge still says that the tests are passing for me.

**Comment by lafrech** [comment]
@wojcikstefan they're still running. (You're too fast!)

**Comment by wojcikstefan** [comment]
Haha, alright, will take a look soon. Thank you for reporting @logsoft !

**Comment by logsoft** [comment]
Thanks for the info! will revert to flask-wtf 0.13 for now. 
For helping out with this my knowledge of flask and web programming sadly is not sufficient enough.

**Comment by eunicekokor** [comment]
Also having this issue!

**Comment by lafrech** [comment]
@eunicekokor Then you're welcome to provide a PR with a fix. I don't mean to be impolite, but note you can use those emoji "reactions" like "thumb-up" as a replacement for "me too" comments to limit email noise for those watching the repo.

@wojcikstefan, none of us seems to have time to take care of this. Would you like to pin flask-wtf version in setup.py in the meantime?

**Comment by lafrech** [comment]
@logsoft, @eunicekokor, can you please confirm latest version in master fixes your issue?

It would be nice to have your feedback before releasing 0.9.1 with the fix.

**Comment by logsoft** [comment]
@lafrech will try these days
