### ISSUE TITLE
Use container-based environment to speed up Travis builds

### ISSUE THREAD

**Issue by lafrech** [MongoEngine/flask-mongoengine#300]
I think we could make the Travis CI tests run faster using container-based environment.

Docs: https://docs.travis-ci.com/user/ci-environment/
Blog article: https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

Here's `umongo`'s `.travis.yml`, as an example: https://github.com/Scille/umongo/blob/master/.travis.yml. It shows how to intall MongoDB using `addons` rather than using `sudo apt-get`.

**Comment by wojcikstefan** [comment]
Good call, thanks @lafrech !
