### ISSUE TITLE
Error when using gunicorn to load app

### ISSUE THREAD

**Issue by berlotto** [MongoEngine/flask-mongoengine#307]
I am trying to load my app trought gunicorn, but PyMongo are showing an error:

```
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] ECONNREFUSED
127.0.0.1 - - [18/Abr/2017:10:17:45 -0300] "GET / HTTP/1.1" 500 - "-" "-"
```

The comand I am using to start is: `gunicorn --worker-class eventlet -w 2 --threads 4 -b :8000 --access-logfile - --error-logfile - atendseg:app`

I see here [https://api.mongodb.com/python/3.1/faq.html#multiprocessing] I need to pass `connect=False` to the MongoClient, but, how I do it in Flask-Mongoengine ?

**Comment by lafrech** [comment]
I don't have the time to try but it could work by adding something like this to your config file:

    MONGODB_CONNECT = False

along with `MONGODB_HOST`, `MONGODB_PORT`, etc.

Everything happens [here](https://github.com/MongoEngine/flask-mongoengine/blob/b5b4609931a48a8982f81a227c3ef91740886964/flask_mongoengine/connection.py), if you want to have a look.

**Comment by berlotto** [comment]
Yes. Thanks.
I debuged the code and I am setting it on MONGODB_SETTINGS dict:

```python
MONGODB_SETTINGS = {
    'db': os.getenv("MONGO_DB", 'default_db_name'),
    'host': os.getenv('MONGO_HOST', "127.0.0.1"),
    'port': os.getenv('MONGO_PORT', 27017),
    'username': os.getenv('MONGO_USERNAME', None),
    'password': os.getenv('MONGO_PASSWORD', None),
    'connect': False,
}
```
