### ISSUE TITLE
Field name with two consecutive underscores

### ISSUE THREAD

**Issue by beilunyang** [MongoEngine/flask-mongoengine#308]
I have an existing DB populated by Mongoose which adds a "__v" (that's two consecutive underscores) field. However, it is not able to be read into a Flask-MongoEngine document even when I declare:
```
class Posts(db.Document):
  title = db.StringField()
  __v = db.IntField()
```
still throws `mongoengine.errors.FieldDoesNotExist: The fields "{'__v'}" do not exist on the document "Posts"`...
How to resolve the problem?

**Comment by lafrech** [comment]
Sounds more like a MongoEngine issue.

Could you try this (not sure it will do any good, just a random thought)?

```python
class Posts(db.Document):
  title = db.StringField()
  v = db.IntField(db_field='__v')
```

**Comment by beilunyang** [comment]
run correctly！ thank you...
