### ISSUE TITLE
jQuery is undefined

### ISSUE THREAD

**Issue by martinhanzik** [MongoEngine/flask-mongoengine#312]
Because flask-debugtoolbar uses jQuery.noConflict(true) (deep noConflict) in toolbar.js, window.$ and window.jQuery are set back to undefined, which makes jQuery in flask-mongoengine debug toolbar unusable. The use of deep noConflict makes sense, so flask-mongonengine toolbar should probably include it's own version of jQuery.

**Comment by martinhanzik** [comment]
Actually, flask-debugtoolbar exposes jQuery in window.fldt.$, so that should probably be used.

**Comment by insspb** [comment]
@martinhanzik Fixed in master
