### ISSUE TITLE
Consider removing ImageField

### ISSUE THREAD

**Issue by spitzbubchen** [MongoEngine/flask-mongoengine#315]
I feel that all files should be treated equally and that it is up to the user to write the necessary code to handle them. ImageField goes beyond the call of duty in that in certain cases it will modify (tamper with) the uploaded file using PIL before saving it to GridFS. In my opinion it is best to keep things as basic and simple as possible.

**Comment by insspb** [comment]
You probably need to write this to mongoengine project, not to related one. we are not handling ImageField in any version that was exist in 2017. 

Sorry for long answer )
