### ISSUE TITLE
Adding MongoDB to Debug Toolbar Panels Overwrites Default List

### ISSUE THREAD

**Issue by nicorellius** [MongoEngine/flask-mongoengine#319]
The docs state to do this to **_add_** the panel:

    from flask import Flask
    from flask_debugtoolbar import DebugToolbarExtension

    app = Flask(__name__)
    app.config['DEBUG_TB_PANELS'] = ['flask_mongoengine.panels.MongoDebugPanel']
    db = MongoEngine(app)
    toolbar = DebugToolbarExtension(app)

But on Ubuntu 16.04 with Flask 0.12.1, Flask-DebugToolbar 0.10.1, and flask-mongoengine 0.9.3, I see only the MongoDB panel. It seems to be overwriting the default panels list with only the MongoDB panel in the list.

Instead, to get this to work, I'm using something like this in my configuration for the application:

    DEBUG_TB_PANELS=[
        'flask_debugtoolbar.panels.versions.VersionDebugPanel',
        'flask_debugtoolbar.panels.timer.TimerDebugPanel',
        'flask_debugtoolbar.panels.headers.HeaderDebugPanel',
        'flask_debugtoolbar.panels.request_vars.RequestVarsDebugPanel',
        'flask_debugtoolbar.panels.template.TemplateDebugPanel',
        'flask_debugtoolbar.panels.logger.LoggingPanel',
        'flask_debugtoolbar.panels.profiler.ProfilerDebugPanel',
        'flask_mongoengine.panels.MongoDebugPanel',
    ],

Am I doing something wrong or are the docs incorrect (It'd be nice to add a single line to add the panel but I was not able to  get that to work)?

I'd be happy to start a pull request to fix the documentation if you think this is correct.

**Comment by insspb** [comment]
Outdated, and I think you already know that you should extend list. When you replace list - you replace it :+1: 

But if you still want to update documentation, PRs are always welcomed.
