### ISSUE TITLE
docs example is missing the view code

### ISSUE THREAD

**Issue by medyagh** [MongoEngine/flask-mongoengine#326]
the doc's example for Add using WTF form is missing the view code, I thought just putting 

```
{{ form }}
```
would do , but it doesnt, is it possible to add a snipiet for the view for adding a Post using WTF?

for reference this the link I am talking about http://docs.mongoengine.org/projects/flask-mongoengine/en/latest/

```
def add_post(request):
    form = PostForm(request.POST)
    if request.method == 'POST' and form.validate():
        # do something
        redirect('done')
    return render_template('add_post.html', form=form)
For each MongoEngine field, the most appropriate WTForm field is used. Parameters allow the user to provide hints if the conversion is not implicit:

PostForm = model_form(Post, field_args={'title': {'textarea': True}})
```

**Comment by insspb** [comment]
@medyagh 
Thank you for report and excuse for long answer. 

New documentation have a lot of examples, like in #497 and have post forms examples too. So not issue anymore. 

The documentation related to new generation engine, as old one is too hard to maintain and deprecated.
