### ISSUE TITLE
Cannot add custom config to Mongo

### ISSUE THREAD

**Issue by ripperdoc** [MongoEngine/flask-mongoengine#327]
Because the way Flask-Mongoengine sanitizes config input, it seems to me some settings in PyMongo are impossible to set. The init_app() method supports a config dict, but it lowercases all keys. Most optional parameters to MongoClient are camelCase, e.g. socketTimeoutMS. I realize that Flask won't accept camelCase config parameters, but there is also no way to add them as extra args to init_app(). Any advice?

**Comment by insspb** [comment]
Hi @ripperdoc
Workaround and fix implemented in #429 and described in current documentation in #477
