### ISSUE TITLE
MongoClient opened before fork. Create MongoClient only

### ISSUE THREAD

**Issue by ufo911** [MongoEngine/flask-mongoengine#333]
I am running Flask with uwsgi threaded mode with processes 4 and using pymongo also flask_mongoengine and uwsgi says "MongoClient opened before fork. Create MongoClient only " I tried connect with connect=False but the result is same

lazy-apps = true problem is fixed but it seems that uwsgi needs more time to load what can be done for best performance ?

**Comment by FlyingDragon0420** [comment]
MONGODB_SETTINGS = [
        {
            "db": "******",
            "alias": "******",
            "host": ["******", "******", "******"],
            "replicaSet": "replSet",
            "ssl": True,
            "ssl_certfile": "{}/app/ca/client.pem".format(DIR_ROOT),
            "ssl_ca_certs": "{}/app/ca/ca.pem".format(DIR_ROOT),
            "ssl_cert_reqs": ssl.CERT_REQUIRED,
            "ssl_match_hostname": False,
            "username": "******",
            "password": "******",
            'authentication_source': 'admin',
            "connect": False,
            "retryWrites": False
        },
        {
            "db": "******",
            "alias": "******",
            "host": ["******", "******", "******"],
            "replicaSet": "replSet",
            "ssl": True,
            "ssl_certfile": "{}/app/ca/client.pem".format(DIR_ROOT),
            "ssl_ca_certs": "{}/app/ca/ca.pem".format(DIR_ROOT),
            "ssl_cert_reqs": ssl.CERT_REQUIRED,
            "ssl_match_hostname": False,
            "username": "******",
            "password": "******",
            'authentication_source': 'admin',
            "connect": False,
            "retryWrites": False
        }
]
I have already set  "connect": False, but the result is same.
