### ISSUE TITLE
How to use advanced queries like in MongEngine?

### ISSUE THREAD

**Issue by nagjanaonline** [MongoEngine/flask-mongoengine#334]
from mongoengine.queryset.visitor import Q

Post.objects(Q(published=True) | Q(publish_date__lte=datetime.now()))

**Comment by ufo911** [comment]
I think such queries have to be implemented in flask-mongoengine core before..

**Comment by bekab95** [comment]
such queries work @insspb can be closed

**Comment by o-brkyr** [comment]
Documentation for this and its implementation through flask_mongoengine does not exist. Could this be elaborated on?
