### ISSUE TITLE
How write test cases for MongoEngine Documents

### ISSUE THREAD

**Issue by prasannaboga** [MongoEngine/flask-mongoengine#337]
I have gone through the [examples/biggerapp](https://github.com/MongoEngine/flask-mongoengine/tree/master/examples/biggerapp) and [MongoEngine docs](http://docs.mongoengine.org/)
implemented MongoEngine Documents to do CRUD operations. Now I am trying to write test cases for  MongoEngine Documents. 

Please suggest how to setup test database for my test case it using develpment database. How to validate error messages.

Here sample code

```python
# app/models/book.py
class Book(db.Document):
    meta = {'collection': 'books'}
    title = db.StringField(required=True, min_length=3, max_length=140, unique=True)
    description = db.StringField(required=True, max_length=200)
    published_at = db.DateTimeFiled(required=True)
    created_at = db.DateTimeField(default=datetime.utcnow)
    updated_at = db.DateTimeField(default=datetime.utcnow)

    def __repr__(self):
        return '<Book - {}>'.format(self.title)

# tests/models/test_book.py
from datetime import datetime, timedelta
from mongoengine import ValidationError
from app.models.book import Book

def test_create_book():
    book = Book()
    book.title = 'Some title'
    book.description = 'Some description'
    book.published_at = datetime.strptime('2016-04-16', '%Y-%m-%d')
    assert book.save()

def test_update_book():
    # TODO define fixture data
    pass

def test_invalid_book():
    book = Book()
    assert not book.save()  # raise ValidationError

```

**Comment by GonerGenesis** [comment]
did you got a proper solution in the end?

**Comment by insspb** [comment]
@prasannaboga 
@GonerGenesis 

I do not understand a question. You can check examples of test in tests directory. They are all are small apps. 
As db you can use docker version of mongoengine. 
Some ideas of how to configure docker can be catched in this WIP: https://github.com/MongoEngine/flask-mongoengine/pull/425
