### ISSUE TITLE
nested listfield doesn't work properly

### ISSUE THREAD

**Issue by Hamifthi** [MongoEngine/flask-mongoengine#339]
hello guys i have a tensorflow object that is a 2 dimensional array and i want to push it to an empty list in mongo i use 3 nested listfield and a floatfield inside it, but it doesn't obey the order of fields that i set i think it skips listfields 
here is sample code:

database file:

    from flask import Flask
    from flask_mongoengine import MongoEngine
    from mongoengine import *
    import datetime

    app = Flask(__name__)
    app.config['MONGODB_DB'] = 'text_similarity'
    app.config['MONGODB_HOST'] = 'mongodb://localhost/text_similarity'
    app.config['MONGODB_PORT'] = 27017
    db = MongoEngine(app)

    class All_contents(Document):
        titles = ListField(StringField())
        tensors = ListField(ListField(ListField(FloatField())))
flask file:

    from flask import Flask, request, jsonify
    from flask_mongoengine import MongoEngine
    from pymongo import MongoClient
    import text_similarity_module
    import database

    app = Flask(__name__)
    db = MongoEngine(app)
    connection = MongoClient('localhost', 27017)
    db_object = connection['text_similarity']
    database.All_contents.objects().update(set__tensors = [], upsert = True)

    tensor_object = text_similarity_module.run_embedding(request.json['text'], graph,
                                                        embed_object, similarity_input_placeholder,
                                                        encoding_tensor, session)
here i want to push tensorflow object that is a 2d array to a list that forms 3d array that has float numbers in it when i try to do this i got error

    database.All_contents.objects().update(push_all__tensors = tensor_object)
but when i change tensorflow object to a 1d array it pushed properly and doesn't obey the order

    database.All_contents.objects().update(push_all__tensors = tensor_object[0])

**Comment by ufo911** [comment]
You may use embeddeddocuments ?

**Comment by Hamifthi** [comment]
it doesn't work that way but my problem solved and i think this is a feature of the mongo db or it is a way of pushing contents to db that this problem happens and i decide to close this issue
