### ISSUE TITLE
Automatic model code generator for mongoengine

### ISSUE THREAD

**Issue by Alexmod** [MongoEngine/flask-mongoengine#377]
I have a ready database mongodb with a very complicated structure.
I understand that I can manually define every field and write the file models.py.
But maybe there is a generator that can query the db and generate the complite file models.py?

For example, there is a generator for SQLAlchemy: 
https://pypi.org/project/sqlacodegen/ 
You give it the db and it generates the ready file models.py

Is there something like this for mongoengine?

**Comment by insspb** [comment]
Not stackoverflow
