### ISSUE TITLE
AUTH_SOURCE Not supported

### ISSUE THREAD

**Issue by kevthehermit** [MongoEngine/flask-mongoengine#381]
I may have missed something but it does not appear that MONGODB_AUTH_SOURCE is supported. 

It is supported in MongoEngine just not the Flask Extensions.

**Comment by nguyenl95** [comment]
@kevthehermit  Yeah that's correct, you can append the "?authSource=<auth-db>" in HOST var instead

**Comment by dilless** [comment]
you can use dictionary settings to provide `authentication_source: 'admin'`. see my issue #386 .

**Comment by insspb** [comment]
@kevthehermit, @nguyenl95  thank you for comments and information. Please take a look, and try to test version in #429 
There is explanation of changes there, and I think it will fix your problem too.

**Comment by insspb** [comment]
Connection/Flask settings documentation updated in #477. Different settings options described. All options except list of dictionaries are deprecated since next version (2.0.0). Please refer to current documentation for more info and settings update.
