### ISSUE TITLE
Rednose setup dependency may interrupt package installation

### ISSUE THREAD

**Issue by r3da-hash** [MongoEngine/flask-mongoengine#382]
In special circumstance,

`rednose`  dependency may interrupt package installation. See bellow, what happening :

```
Download error on https://pypi.org/simple/rednose/: [Errno 97] Address family not supported by protocol -- Some packages may not be found!
Couldn't find index page for 'rednose' (maybe misspelled?)
Download error on https://pypi.org/simple/: [Errno 97] Address family not supported by protocol -- Some packages may not be found!
No local packages or working download links found for rednose
```

python version `3.8.2`

Does we need absolutely this dependency ? Could be remove it in order to avoid this type of issue ?

https://github.com/MongoEngine/flask-mongoengine/blob/master/setup.py#L52

**Comment by insspb** [comment]
Hi @r3da-hash, how to reproduce this error? Just installed on python 3.8 without any problem. 
What OS and commands do you use, and what version.

**Comment by r3da-hash** [comment]
Hi @insspb ,

This issue is similar to https://github.com/MongoEngine/flask-mongoengine/issues/371

Sorry , I can't reproduce this now.
I think that `rednose` package is now available ...

But, this package may not be defined as `setup_required`.

Do you think that a plugin for adding colour to tests console output should be consider as a setup requirement ?

**Comment by insspb** [comment]
@r3da-hash #380 fixed. I think this may considered as fix. Please reopen if I am wrong. 
This fix available ONLY in master branch for this moment.
