### ISSUE TITLE
Debug Toolbar operation_tracker _unpack_response fails when it encounters a CommandCursor

### ISSUE THREAD

**Issue by geoffdavis** [MongoEngine/flask-mongoengine#384]
I'm working on some embedded documents within an aggregation. Due to the level of nesting involved, it seems that a CommandCursor filters it's way down to the wrapped `_unpack_response` function in `operation_tracker.py`.

The failure occurs when the wrapper tries to get the length of the "response" object. CommandCursors (as returned by the aggregation function in pymongo >= 3) are iterators, and don't have a length attribute to them.

A workaround for this is to change the function definition to check for instances of CommandCursor, and convert it to a dict first before running len() on it.

```python
# Wrap helpers._unpack_response for getting response size
@functools.wraps(_original_methods["_unpack_response"])
def _unpack_response(response, *args, **kwargs):
    result = _original_methods["_unpack_response"](response, *args, **kwargs)
    if isinstance(result, pymongo.command_cursor.CommandCursor):
        rlen = len(list(response))
    elif hasattr(response, "__length__"):
        rlen = len(response)
    else:
        rlen = 0
    response_sizes.append(sys.getsizeof(response, rlen) / 1024.0)
    return result
```

**Comment by insspb** [comment]
Hi @geoffdavis  thank you for report. Debug toolbar completely refactored from scratch. Now it does not patch anything at all. 
Available in master or in next version. Docs on read the docs. Now it working on pymongo level with internal monitoring.
