### ISSUE TITLE
MONGODB_ prefix not working

### ISSUE THREAD

**Issue by jobrachem** [MongoEngine/flask-mongoengine#385]
In my app, this code works fine:

```python
MONGODB_SETTINGS = {}
MONGODB_SETTINGS["host"] = "localhost"
MONGODB_SETTINGS["port"] = 27017
MONGODB_SETTINGS["db"] = "mortimer"
MONGODB_SETTINGS["username"] = None
MONGODB_SETTINGS["password"] = None
```

And with this code, authentication fails.

```python
MONGODB_HOST = "localhost"
MONGODB_PORT = 27017
MONGODB_DB = "mortimer"
MONGODB_USERNAME = "user_admin"
MONGODB_PASSWORD = "admin"
```

It should both work, right?

**Comment by dilless** [comment]
I think it's not the MONGODB_ prefix error.
In your second block of code, you provid username and password to connect to the mongodb server, so you should provide `authentication_source: 'admin'` to `MongoEngine.connect()`. But individual settings seems do not support that. 
You can provid `authentication_source: 'admin'` to your dictionary settings to fix this error. See my issue #386 for more detail.

**Comment by jobrachem** [comment]
Seems to me like both of these are unexpected behavior. I'd expect the authentication source be default to `admin`, because that is the MongoDB default, too.

**Comment by insspb** [comment]
Should add some docs in #400 

@jobrachem thank you gor pointing. 

By the way, it seems not full config. ? Or I miss something. 
Can you share whole flask app and db init code you are using.

**Comment by insspb** [comment]
@jobrachem, @dilless thank you for comments and information. Please take a look, and try to test version in #429 
There is explanation of changes there, and I think it will fix your problem too.

**Comment by insspb** [comment]
Connection/Flask settings documentation updated in #477. Different settings options described. All options except list of dictionaries are deprecated since next version (2.0.0). Please refer to current documentation for more info and settings update.
