### ISSUE TITLE
Custom config feature of MongoEngine init not described

### ISSUE THREAD

**Issue by insspb** [MongoEngine/flask-mongoengine#400]

**Comment by VetriMaaran** [comment]
``` app.config['MONGODB_SETTINGS'] = {
    'host': MONGODB_URL
}
```
This will work

**Comment by insspb** [comment]
Connection/Flask settings documentation updated in #477. Different settings options described. All options except list of dictionaries are deprecated since next version (2.0.0). Please refer to current documentation for more info and settings update.
