### ISSUE TITLE
Can't install flask-mongoengine in my virtual environment

### ISSUE THREAD

**Issue by keerthivasan-g** [MongoEngine/flask-mongoengine#402]
pip install flask-mongoengine
Collecting flask-mongoengine
  Using cached flask-mongoengine-0.9.5.tar.gz (111 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\keerthivasan\desktop\pybox\venv\scripts\python.exe' -c 'import
 sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\keerthivasan\\AppData\\Local

\\Temp\\pip-install-su4c26f2\\flask-mongoengine\\setup.py'"'"'; __file__='"'"'C:\\User
s\\keerthivasan\\AppData\\Local\\Temp\\pip-install-su4c26f2\\flask-mongoengine\\setup.
py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"
'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg
_info --egg-base 'C:\Users\keerthivasan\AppData\Local\Temp\pip-pip-egg-info-xw613uem'
         cwd: C:\Users\keerthivasan\AppData\Local\Temp\pip-install-su4c26f2\flask-mong
oengine\

im trying to install flask-mongoengine but can't for some reasons. Help me out

**Comment by vinu76jsr** [comment]
Can you install anything else or is it just a problem with flask-mongoengine

**Comment by keerthivasan-g** [comment]
> Can you install anything else or is it just a problem with flask-mongoengine

problem with flask-mongoengine only

**Comment by vinu76jsr** [comment]
if there is a permission issue or python conflict in windows, usually explicitly specififying pip module helps, `python -m pip install flask-mongoengine`

**Comment by christopherpross** [comment]
Hey, I can reproduce this issue.
I don't know, but maybe this is because I use python 3.8 here? Here is the output. The idea at the last comment doen't work, it produce the same output. here is it:

(venv) chpross@vmd21292:~/project-elrond$ python3 -m pip install flask-mongoengine
Collecting flask-mongoengine
  Using cached flask-mongoengine-0.9.5.tar.gz (111 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/chpross/project-elrond/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qgz3p0ke/flask-mongoengine/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qgz3p0ke/flask-mongoengine/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-qgz3p0ke/flask-mongoengine/pip-egg-info
         cwd: /tmp/pip-install-qgz3p0ke/flask-mongoengine/
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /home/chpross/project-elrond/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-uuurfyzw/rednose/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-uuurfyzw/rednose/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ydfi3ngu
           cwd: /tmp/pip-wheel-uuurfyzw/rednose/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for rednose
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/home/chpross/project-elrond/venv/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/chpross/project-elrond/venv/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp3z90mx39', '--quiet', 'rednose']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qgz3p0ke/flask-mongoengine/setup.py", line 36, in <module>
        setup(
      File "/home/chpross/project-elrond/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/chpross/project-elrond/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/chpross/project-elrond/venv/lib/python3.8/site-packages/setuptools/dist.py", line 718, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/home/chpross/project-elrond/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "/home/chpross/project-elrond/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/chpross/project-elrond/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/chpross/project-elrond/venv/lib/python3.8/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/chpross/project-elrond/venv/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/home/chpross/project-elrond/venv/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp3z90mx39', '--quiet', 'rednose']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(venv) chpross@vmd21292:~/project-elrond$

**Comment by vinu76jsr** [comment]
@christopherpross can you share your environment(OS version) python version etc, I will try to reproduce it on my system if it is linux/mac.

**Comment by christopherpross** [comment]
@vinu76jsr hey, of curse:

- python  64 bit, version: 3.8.2 (GCC 9.3.0)
- ubuntu: Ubuntu 20.04 LTS (64 bit)
- shell: bash

hope it helps.

**Comment by insspb** [comment]
@keerthivasan-g @christopherpross 
Please try master version.

**Comment by wangyu190810** [comment]
@christopherpross master version install success.

**Comment by arthuravila26** [comment]
same here! Already using master version.

**Comment by radome** [comment]
I had the same problem with Python 3.7.8 installing from PyPI. Installing from master works fine but I was wondering if there's a plan to publish new releases as the latest release on GitHub is 0.9.2 (Feb 2017), PyPI is 0.9.5 (Feb 2018) and the current setup.py is 0.10.7.

Thanks!

**Comment by lucassimon** [comment]
Same problem here 

```bash
$ python3 
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

ubuntu: Ubuntu 20.04 LTS (64 bit)
shell: zsh
```

```bash
$ pip install -r requirements/dev.txt
Requirement already satisfied: Flask in ./.venv/lib/python3.8/site-packages (from -r requirements/base.txt (line 1)) (1.1.2)
Collecting Flask-RESTful
  Using cached Flask_RESTful-0.3.8-py2.py3-none-any.whl (25 kB)
Collecting python-dotenv
  Using cached python_dotenv-0.14.0-py2.py3-none-any.whl (17 kB)
Requirement already satisfied: pymongo in ./.venv/lib/python3.8/site-packages (from -r requirements/base.txt (line 4)) (3.11.0)
Collecting flask-mongoengine
  Using cached flask-mongoengine-0.9.5.tar.gz (111 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/lucas/workspaces/plataformafii/apis/api-plataforma-fii/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k1g0t687/flask-mongoengine/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k1g0t687/flask-mongoengine/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-k1g0t687/flask-mongoengine/pip-egg-info
         cwd: /tmp/pip-install-k1g0t687/flask-mongoengine/
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /home/lucas/workspaces/plataformafii/apis/api-plataforma-fii/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-z8t7tfli/rednose/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-z8t7tfli/rednose/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-alm6064h
           cwd: /tmp/pip-wheel-z8t7tfli/rednose/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for rednose
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/home/lucas/workspaces/plataformafii/apis/api-plataforma-fii/.venv/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/lucas/workspaces/plataformafii/apis/api-plataforma-fii/.venv/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpyp1dkgh9', '--quiet', 'rednose']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-k1g0t687/flask-mongoengine/setup.py", line 36, in <module>
        setup(
      File "/home/lucas/workspaces/plataformafii/apis/api-plataforma-fii/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 164, in setup
        _install_setup_requires(attrs)
      File "/home/lucas/workspaces/plataformafii/apis/api-plataforma-fii/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 159, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/lucas/workspaces/plataformafii/apis/api-plataforma-fii/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 699, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/home/lucas/workspaces/plataformafii/apis/api-plataforma-fii/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 779, in resolve
        dist = best[req.key] = env.best_match(
      File "/home/lucas/workspaces/plataformafii/apis/api-plataforma-fii/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1064, in best_match
        return self.obtain(req, installer)
      File "/home/lucas/workspaces/plataformafii/apis/api-plataforma-fii/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1076, in obtain
        return installer(requirement)
      File "/home/lucas/workspaces/plataformafii/apis/api-plataforma-fii/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/lucas/workspaces/plataformafii/apis/api-plataforma-fii/.venv/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/home/lucas/workspaces/plataformafii/apis/api-plataforma-fii/.venv/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpyp1dkgh9', '--quiet', 'rednose']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by cicciodifranco** [comment]
Hey. 
I had the same problem but i found this on [stackoverflow](https://stackoverflow.com/questions/34819221/why-is-python-setup-py-saying-invalid-command-bdist-wheel-on-travis-ci).

`pip install wheel` and then `pip install flask-mongoengine` worked for me.

**Comment by RammusXu** [comment]
I guess it relate to https://github.com/pypa/setuptools/issues/1934#issuecomment-561938312

Caused by
https://github.com/MongoEngine/flask-mongoengine/blob/93bd9b9b8803ffae1ca9dd6435c2108c02a0403e/setup.py#L54

**Comment by shenmou98** [comment]
> Hey.
> I had the same problem but i found this on [stackoverflow](https://stackoverflow.com/questions/34819221/why-is-python-setup-py-saying-invalid-command-bdist-wheel-on-travis-ci).
> 
> `pip install wheel` and then `pip install flask-mongoengine` worked for me.

Thanks, this work for me.  (  `pip install wheel` and then `pip install flask-mongoengine`  )

**Comment by kynan** [comment]
The problem is that that [there is no Python 3 wheel](https://pypi.org/project/flask-mongoengine/#files) for flask-mongoengine 0.9.5, see #410.

**Comment by insspb** [comment]
Hi, dear all. 

Thank you for patience. Unfortunately (or maybe hopefully?) i am currently has no flask or mongo related projects, so my time here is very limited. After some fight with travis, I was able to deploy new version to pip. Please check.

**Comment by qre0ct** [comment]
This still does not seem to be working. I keep getting the same error:

```
vagrant@ubuntu-xenial:~$ sudo pip install --upgrade flask-mongoengine
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
WARNING: The directory '/home/vagrant/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting flask-mongoengine
  Downloading flask-mongoengine-1.0.0.tar.gz (117 kB)
     |################################| 117 kB 2.0 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpsDsEsP
       cwd: /tmp/pip-install-qSP05Q/flask-mongoengine
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 243, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 12, in <module>
      long_description = open(doc_path, encoding="utf-8").read()
  TypeError: 'encoding' is an invalid keyword argument for this function
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpsDsEsP Check the logs for full command output.
```

I have also tried `pip install wheel` and then `pip install flask-mongoengine` but it does not seem to solve the problem. Can someone please help me understand :

1. What's the problem here? Am I missing something?
2. What can I do to solve the issue?

**Comment by insspb** [comment]
@qre0ct The answer to your question is in second line of copy/paste.
We do not support python 2.7 any more.
