### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by bagerard** [MongoEngine/flask-mongoengine#414]
Hi, is there anything preventing from triggering a release (0.10.0) out of master?

I've seen some people installing from master and last release 0.9.5 is from 2018 so it would be good to release the work that was done

**Comment by onlinejudge95** [comment]
+1

**Comment by insspb** [comment]
@bagerard @onlinejudge95 After some fight with travis and access permissions I was able to make a new release. Please test.

**Comment by bagerard** [comment]
Great news, thanks for making it happen

**Comment by onlinejudge95** [comment]
@insspb bro, any plans on fixing some sort of release cycle, just saying because we are here in case of any help required.

BDW nice work
