### ISSUE TITLE
Remove 1.0.0 and Stop Releasing Future Version for Python 3.5

### ISSUE THREAD

**Issue by jhwei** [MongoEngine/flask-mongoengine#421]
I saw the new version 1.0.0 had dropped support for Python 3.5, so would it be a good idea to freeze the version for Python 3.5 at 0.9.5?

**Comment by StephenBrown2** [comment]
Do you mean pinning the requirement in your project to `flask-mongoengine<1.0.0` or `flask-mongoengine==0.9.5`?

**Comment by jhwei** [comment]
@StephenBrown2 That will definitely do the same thing. But I mean 1.0.0 doesn't support Python 3.5 anymore so I think it should be removed from the PyPI release for py3.5.
Some other software will publish a new version based on the python version. For example, the newest version for py3.5 would be 0.9.5, 1.0.0 for py3.6, 1.0.0 for py3.7 and so on. I also understand other software will just publish one version for the whole py3 version. 
I don't know if flask-mongoengine has separate PyPi releases for different Python versions, if it does, 1.0.0 should be removed for py3.5.

**Comment by StephenBrown2** [comment]
It looks like the 3.5 classifier has already been removed from setup.py: https://github.com/MongoEngine/flask-mongoengine/blob/master/setup.py#L66-L67 so pip should not install 1.0.0 for python versions less than 3.6.
`flask-mongoengine` is not released as a compiled package, so there is only a `py3` wheel https://pypi.org/project/flask-mongoengine/#files.
I would recommend that projects that depend on `flask-mongoengine` and can't update to py3.6+ pin the dependency, as it seems that all the necessary steps have been completed.

**Comment by jhwei** [comment]
@StephenBrown2 Thanks for the explanation. `pip` will install 1.0.0 for python 3.5, but 0.9.5 for python 2.7. I will follow the suggestion of setting `flask-mongoengine==0.9.5` for the py3.5 project.

**Comment by StephenBrown2** [comment]
Looking into it a little further, I found that in fact the necessary step hadn't been taken, to specify `python_requires` in `setup.py` as well. I've submitted a PR to fix it, but since 1.0.0 is already released, I don't know if @insspb can re-release it, or if it will need to be a 1.0.1 release.

**Comment by jhwei** [comment]
@StephenBrown2 I don't know how `python_requires` work when publishing wheel. mongoengine does specify `>=3.6` in their [recent commit](https://github.com/MongoEngine/mongoengine/commit/0014346de1216ec0b1422bd42ff422bd52f95106), but I still get 0.22.0 (which drops py3.5 support) under py3.5 environment.

**Comment by bagerard** [comment]
MongoEngine 0.22.0 dropped support for 3.5 (by introducing f-strings) but the update to `python_requires` was comited after 0.22.0 was released and so isn't yet published on pypi. I'll publish that as 0.22.1 shortly
