### ISSUE TITLE
uuid in mongoengine is saving as binary 

### ISSUE THREAD

**Issue by rohan2734** [MongoEngine/flask-mongoengine#440]
uuid in mongoengine is saving as binary 

![image](https://user-images.githubusercontent.com/58523134/117532137-a4ba5f00-b003-11eb-8263-0fc936a63786.png)

the model of the blog here is

![image](https://user-images.githubusercontent.com/58523134/117532146-b3087b00-b003-11eb-88f5-3b251dd7c2be.png)

and the uuid generations code is  
```python
blogID=uuid.uuid4()

```
but when i check the database it is not saving in the form of `ab304cc9-1849-48f8-86a0-0ac39ff9929d`

it is saving in some binary format, how to save the blogID here, in the form of `ab304cc9-1849-48f8-86a0-0ac39ff9929d` 
instead of binary?

**Comment by bagerard** [comment]
THe UUIDField indeed gets stored natively as binary but you can specify `UUIDField(binary=False)`  ([doc](https://docs.mongoengine.org/apireference.html#mongoengine.fields.UUIDField))

see below

import uuid
class TR(Document):
    u1 = UUIDField()
    u2 = UUIDField(binary=False)

TR(u1=uuid.uuid1(), u2=uuid.uuid1()).save()

**Comment by rohan2734** [comment]
sir i am using 
`u1= uuid.uuid4()`
but you have sown me
`uuid.uuid1()`
is it fine to use `uuid1` just for the sake of binary?

**Comment by bagerard** [comment]
choosing between uuid1 or uuid4 is up to you, UUIDField works with both...
