### ISSUE TITLE
check_keys support

### ISSUE THREAD

**Issue by zloyded** [MongoEngine/flask-mongoengine#441]
MyModel.save() is not support check_keys argument, but mongoengine support. How can i pass check_keys to mongoengne .insert()?

**Comment by insspb** [comment]
@zloyded Excuse for long answer. 
I tried to understand what you mean, but did not find this argument in mongoengine. (Search: https://docs.mongoengine.org/search.html?q=check_keys&check_keywords=yes&area=default)

Probably your question should be pointed to base project, as we do not modify save method anyhow in any version.
