### ISSUE TITLE
Is the package still maintained?

### ISSUE THREAD

**Issue by pythonhubpy** [MongoEngine/flask-mongoengine#446]
This Flask Mongoengine package is really great but I really had a doubt that whether this package is still maintained. Because there is no commits since last year.

**Comment by insspb** [comment]
@pythonhubpy Commits and help is welcome here. 
This package has a huge pull request queue, and I will fix it after finishing my current project. (Expected in November). 

Unfortunately, currently I am not working with Flask or Mongo, so context switch is difficult for me.

**Comment by pythonhubpy** [comment]
Sure thanks a lot. Same with myself so much occupied thought of making a PR but schedule is so bust will make PR soon
