### ISSUE TITLE
It is necessary to close connection after a request to the data base?

### ISSUE THREAD

**Issue by dmtzs** [MongoEngine/flask-mongoengine#447]
Hello everyone,

I'm implementing flask-mongoengine as the documentation explains but I have a doubt and in my case I'm I initiating through this library in my __init__.py so I can import the variable that will have the MongoEngine instance. In the endpoints after a request I should close the connection? Or flask-mongoengine close this connection automatically? I'm asking this because it is not clear at all in the documentation and also to know if something happens if its the case that many users requests an endpoint of my API that will need to do this connection to the database, so someone knows if the connection should be closed or this is handled automatically by flask_mongoengine?

Thank you everyone in advance for your help

**Comment by bagerard** [comment]
MongoEngine connection is designed to be globally available, i.e instantiated once per process, usually in the "__init__.py" where the application is bootstrapped (somewhere near the `app = Flask(...)` code ), and then simply accessed (by using the Document classes) by the different threads. You shouldn't have to care about closing connection as long as you aren't instantiating new connections on every request but that shouldn't be the case.

**Comment by dmtzs** [comment]
Thank you for your answer, now it's very clear, thank you for your help
