### ISSUE TITLE
Please package testsuite to the distribution tarball

### ISSUE THREAD

**Issue by mcepl** [MongoEngine/flask-mongoengine#450]
I would like to fix packaging for OpenSUSE, but your release tarball does not contain the tests directory. Could you please distribute them as well?

**Comment by insspb** [comment]
Hi @mcepl 
I do not understand a problem, why you cannot use Github directly and how all this works in OpenSUSE.

Honestly, I am not supporting distribution of non-core python packages like ours outside pypi. 

Anyway there is a lot of other and more important issues right now. So if you want to change some in distribution the only one possible way to make a pull request and discuss proposed changes, when everything became clear. 

Thank you, and excuse me that I cannot help here.

**Comment by mcepl** [comment]
Well, developers are usually interested in more users, more testing (including archaic platforms), and some patches, but obviously you are all set so we well do what we need to do without you. Or perhaps not.
