### ISSUE TITLE
MongoEngine models Field missing

### ISSUE THREAD

**Issue by liuwenzhi0318** [MongoEngine/flask-mongoengine#500]
example：

class User(db.Document):
    email = db.StringField(required=True)
    first_name = db.StringField(max_length=50)
    last_name = db.StringField(max_length=50)
![image](https://user-images.githubusercontent.com/37536326/182991497-fb9c7bdc-b965-4160-ab81-13df7315d94d.png)

 I setup flask-mongoengine 1.0
![image](https://user-images.githubusercontent.com/37536326/182991172-fa4ca85c-0f6c-4bd8-b268-1561bc4c11bd.png)

And I see that the master branch _init_.py has these
![image](https://user-images.githubusercontent.com/37536326/182991270-8cba1ada-ec5b-4fd1-b81c-531549b976d3.png)

**Comment by insspb** [comment]
@liuwenzhi0318 Not clear what you mean. 
Shortly. Version 1.0 works with monkeypatching. IDE will highlight fields as not existed, but they will work. 

Current master use normal python nesting and getters. It is more IDE friendly, but again any field will work in one way or anotherr (check current docs how it works)

Current master version was not released (this will be 2.0).

**Comment by insspb** [comment]
No additional information from issue author + Probably solved in current developer's version. Closed

@liuwenzhi0318 please reopen, if you have additional info.
