### ISSUE TITLE
AttributeError: type object 'Collection' has no attribute 'insert'

### ISSUE THREAD

**Issue by Nawaphong-13** [MongoEngine/flask-mongoengine#513]
error
```
File: "/flask_mongoengine/operation_tracker.py", line 27, in <module>
    "insert": pymongo.collection.Collection.insert,
AttributeError: type object 'Collection' has no attribute 'insert'
```

**Comment by insspb** [comment]
Hi @Nawaphong-13 probably you use current pip version. This module was completely redesigned and rewritten in current master. 
If you need flask-mongoengine only for debug toolbar, I think it is safe to test master. 
If you use flask-mongoengine for form generation or with flask-admin, it is better to wait until release, as such modules in rewrite process, and currently I am busy on main work. I am expect release in this year, but with no concrete date at this point, as I am alone now :) Pre-releases expected at end of October.

Please confirm what version do you use.

**Comment by Nawaphong-13** [comment]
@insspb 

flask-mongoengine==1.0.0
pymongo==4.2.0
pip==22.1.1

**Comment by insspb** [comment]
@Nawaphong-13 thanks for confirmation. This was a reason why this module was rewritten in current master.
