### ISSUE TITLE
model_fields with (only or exclude colums) = broken fields order

### ISSUE THREAD

**Issue by rustamakhmetov** [MongoEngine/flask-mongoengine#53]
In flask_mongoengine/wtf/orm.py lines 229, 231

ps. sorry for my english

**Comment by lafrech** [comment]
Is this fixed?

I see the https://github.com/MongoEngine/flask-mongoengine/pull/63 was closed not merged, but part of it is in the code, so I'd say it is fixed.

Still, I'm wondering.

```python
    if only:
        field_names = [x for x in only if x in set(field_names)]
    elif exclude:
        field_names = [x for x in field_names if x not in set(exclude)]
```

From what I see here, `exclude` does not modify the `order` from `field_name`, however, when using `only`, it looks like the order is the order in `only`, not the initial order in `field_name`.

Shouldn't it be like this?

```python
    if only:
        field_names = [x for x in field_names if x in set(only)]
```

(Not sure what `set` is here for, BTW.)

Or is this intended to allow the user to specify a different order using `only`?

**Comment by insspb** [comment]
@lafrech @rustamakhmetov 
Thank you for report. Almost 10 years passed :) 

This issue does not exist in version v1.0.0. This issue documented during current work in #483, So I am closing this one.
