### ISSUE TITLE
.save() does not work

### ISSUE THREAD

**Issue by Ivan8R** [MongoEngine/flask-mongoengine#65]
flask 0.10.1, python 2.7.5, mogoengine 0.8.3, mongoDB v2.4.5, 
I'm trying to save User with schema
class User(Document):
    email = StringField(required=True)
    first_name = StringField(max_length=50)
    last_name = StringField(max_length=50)

ross = User(email='ross@example.com', first_name='Ross', last_name='Lawley').save()
and happen nothing,  after save(),nothing is stored in the mongodb, db is empty

**Comment by lafrech** [comment]
This should work. Since the question is 2.5 years old, I'm closing the issue. Please reopen if needed.
