### ISSUE TITLE
Connection by MongoDB URI

### ISSUE THREAD

**Issue by jvc26** [MongoEngine/flask-mongoengine#66]
I think it would be cleaner to enable configuration using a [MongoDB URI](mongodb://cellcountr:test@192.168.33.10/cellcountr), which can be parsed to fill in the required environment variables.

For example, storing a simple 1-variable URI in the environment

MONGODB_URI = 'mongodb://test:test@test.com/testdb'

Which is then parsed and used for the connection, if present.

Is there a design choice to *not* enable this feature, or is it something you'd consider a patch for?

**Comment by lafrech** [comment]
From what I understand of `_create_connection`, I think this is obsolete:

```python
    # Handle uri style connections
    elif "://" in conn.get('host', ''):
        uri_dict = uri_parser.parse_uri(conn['host'])
        conn['db'] = uri_dict['database']

    return mongoengine.connect(conn.pop('db', 'test'), **conn)
```

Should this issue be closed?

**Comment by losintikfos** [comment]
This has been resolved.
