### ISSUE TITLE
DynamicDocument: IntField returns as an ObjectId Field

### ISSUE THREAD

**Issue by nfarrar** [MongoEngine/flask-mongoengine#68]
I have an IntField in my DynamicDocument that is being returned as an 'ObjectId' field.  
If I query the field directly in mongo, I see: 
```
    { "fid" : 10200331 }
```

However if I print the field using flask-mongoengine, I see a hash of the int value and if I print the type, I see: 
```
     <class 'bson.objectid.ObjectId'> 
```
When it should be:
```
     <type 'unicode'>.
```

My model is defined like this: 
```python
    class Alert(db.DynamicDocument):
        meta = {'collection': 'alerts'}
        fid = db.IntField(required=True, unique=True)

        def __init__(self, **kwargs):
            kwargs['fid'] = kwargs['id']
            kwargs.pop('id')
            super(Alert, self).__init__(**kwargs)
```
I've got other integers that are being interpreted correctly, but this is not.  Any idea what's going on?

**Comment by lafrech** [comment]
This is more than 2 years old. Can you reproduce?

**Comment by lafrech** [comment]
Please reopen if you can reproduce.
