### ISSUE TITLE
Unicode error on debug toolbar

### ISSUE THREAD

**Issue by rochacbruno** [MongoEngine/flask-mongoengine#72]
The same issue as reported here https://github.com/mgood/flask-debugtoolbar/issues/55

**Comment by lafrech** [comment]
Fixed in debug toolbar ?

https://github.com/mgood/flask-debugtoolbar/commit/82295aa4aa4b2083e2e707004cd95ce0f48a7819
https://github.com/mgood/flask-debugtoolbar/commit/10c03880c725f74378f773d53f704c5cc4adb0a0 

Or still an issue here?

**Comment by wojcikstefan** [comment]
My guess is that it's not an issue anymore and this can be closed. Our requirements.txt specifies `Flask-DebugToolbar>=0.8` so the fixes should be included in all new builds.

(also this issue is from 2013).
