### ISSUE TITLE
[RFE] Reap expired sessions

### ISSUE THREAD

**Issue by abn** [MongoEngine/flask-mongoengine#73]
It would be great if there was an option to allow users to enable some form of reaping of expired sessions. A suggested solution might be to reap if an expired session is encountered, this way reaping is seamless. The alternative is to provide a user callable method to perform a clean up.

**Comment by lafrech** [comment]
Not sure I understand the term "reap".

If you mean delete expired sessions, this is automatic thanks to TTL index: https://github.com/MongoEngine/flask-mongoengine/issues/199

Otherwise, please reopen.
