### ISSUE TITLE
Debug toolbar panel does not work on Python 3

### ISSUE THREAD

**Issue by cwygoda** [MongoEngine/flask-mongoengine#75]
Trying to get the debug toolbar panel work with Python 3.3 needs a couple of small code tweaks.

Many tests fail then though, but that might be more generally a problem with Python 3 and Flask-MongoEngine?

See arsgeografica/flask-mongoengine@bf9d237202a62f73c2a0ec90383e26bd40a13187 for my changes.

**Comment by lafrech** [comment]
Is this still an issue? I'm using Debug Toolbar on Python 3.4.2 and it seems fine.
