### ISSUE TITLE
Connection/cache problem (I think)

### ISSUE THREAD

**Issue by odra** [MongoEngine/flask-mongoengine#81]
Hello,

Yesterday I got a awkward problem when trying to save/querying documents.

Suddenly my flask application was always returning 0 documents from the database, then I tried to create new ones, but those documents/objects weren't being added in mongo.

When I tried to query the collection again in MongoEngine it only returned those new objects/documents but did not return the ones in the database.

After a while, I decided to remove Flask-MongoEngine from my application, and it worked just fine. That moment I realized that reading your source code you do not implement the "teardown" method in MongoEngine class (which I implemented myself and the bug stopped).

I do not know if this a connection pool issue, but it seems that the data saved/retrieved ended up in some kind of deadlock.

Thanks.

**Comment by lafrech** [comment]
Thanks for reporting. Any way to reproduce?

**Comment by wojcikstefan** [comment]
This can probably be closed given that there's no way to reproduce the issue and the OP seems unresponsive.
