### ISSUE TITLE
Use pk instead of id to build QuerySetSelectField

### ISSUE THREAD

**Issue by ripperdoc** [MongoEngine/flask-mongoengine#82]
For model objects that use a custom primary_key, the process_formdata() method will try to fetch the instance using id, which raises InvalidQueryError. If switched to pk, it works fine!

**Comment by lafrech** [comment]
Fixed?

https://github.com/MongoEngine/flask-mongoengine/commit/b6df83242128c3c383696eae2057bd3725c3139e#diff-5de699a09ebf5c0422e6ea179c6585fb
