### ISSUE TITLE
use of "unicode" breaks JsonField and children in Python3

### ISSUE THREAD

**Issue by NickRSearcy** [MongoEngine/flask-mongoengine#87]
The issue is due to the use of Python2 "unicode" in line 137 of [`fields.py`](https://github.com/MongoEngine/flask-mongoengine/blob/master/flask_mongoengine/wtf/fields.py)

I'll submit a pull request with a fix in a few minutes.

**Comment by sladinji** [comment]
It would be great if your fix was merged into master branch...

**Comment by losintikfos** [comment]
@NickRSearcy Did you submit a pull request for this?

**Comment by losintikfos** [comment]
Issue resolved. Thanks
