### ISSUE TITLE
Error: When i set app.config['MONGODB_PORT']

### ISSUE THREAD

**Issue by mxck** [MongoEngine/flask-mongoengine#94]
File "/Users/mxck/auction-test/lib/python2.7/site-packages/flask_mongoengine/__init__.py", line 44, in init_app
    'port': int(app.config.get('MONGODB_PORT', 0)) or None
TypeError: int() argument must be a string or a number, not 'tuple'

**Comment by lafrech** [comment]
Looks like in you configuration `MONGODB_PORT` is a tuple rather than an integer.

Hard to tell more without you settings file.

(And I think you code is equivalent to `'port': int(app.config.get('MONGODB_PORT', None))`

Please reopen if needed.
