### ISSUE TITLE
critical bug fails to expire sessions even after permanent session expiry

### ISSUE THREAD

**Issue by takinbo** [MongoEngine/flask-mongoengine#95]
As a result of a difference in referenced current time in [L60](https://github.com/MongoEngine/flask-mongoengine/blob/master/flask_mongoengine/sessions.py#L60) and [L71](https://github.com/MongoEngine/flask-mongoengine/blob/master/flask_mongoengine/sessions.py#L71) when saving and retrieving sessions, permanent sessions either expire earlier (if you're west of prime meridian) or later than expected.

**Comment by lafrech** [comment]
I believe this was fixed in https://github.com/MongoEngine/flask-mongoengine/commit/603e5690cfe29bbf49b16b090e82aea43de3cd65.

**Comment by takinbo** [comment]
I haven't tested this but it appears this has been fixed by this commit. Closing the issue.
