### ISSUE TITLE
add mongomock if app.config['TESTING']

### ISSUE THREAD

**Issue by ocean1** [MongoEngine/flask-mongoengine#98]
i would love to be able to have a mongomock connection if app.config['TESTING'] is true
this would allow easier testing of the flask application (otherwise an in-memory mongo like the one implemented in ming would be great)

**Comment by aviau** [comment]
+1

**Comment by sri85** [comment]
+1

**Comment by brunobelarmino** [comment]
+1

**Comment by losintikfos** [comment]
I will be looking into adding this to the milestone.

Thanks

**Comment by losintikfos** [comment]
Target
--
- Create a temporary `mongod` instance for testing purposes only. The presence of setting `app.config['TESTING']` will instruct `Flask-MongoEngine` bootstrap to provide temporary `mongod` instance else a valid instance connection is established and provided instead.

**Comment by brunobelarmino** [comment]
@losintikfos why not use mongomock like mongo engine? 
I think the best solution is change the "_create_connection" method of flask-mongoengine to not call pymongo "uri_parser.parse_uri" method when it contains the protocol: "mongomock://" like the mongoengine team has done (https://github.com/MongoEngine/mongoengine/commit/23f07fde5e88c42c42f26ca48edd10456c7babbf).

The problem is the current version of mongo engine (0.10.5) doens't support it yet. But the next version (0.10.6) will.

What do you think about?

**Comment by losintikfos** [comment]
@brunobelarmino so similarly to MongoEngine - check for the connection string protocol construct instead of the app.config['TESTING'] setting?

**Comment by brunobelarmino** [comment]
@losintikfos IMHO it is the better solution. :smile:  

let me know yours.

**Comment by losintikfos** [comment]
@brunobelarmino I did not patronise nor pooped your suggestion. I was enquiring for confirmation to ensure you meant avoid using setting app.config['TESTING'], but instead check for the connection string protocol construct.

**Comment by brunobelarmino** [comment]
Sorry whether my message seems selfish. But it isnt the intention.

I think flask-mongoengine shouldnt decide whats the best way to test apps. For example: create a mongod instance, use a existing mongod instance or use mongomock.

I think the best solution is turn flask-mongoengine flexible and working with all this approaches.

But my point is today flask-mongoengine doesnt work with mongomock. I Think when the app.config['TESTING'] is true we could by pass de pymongo uri validation. Additionally would be nice have a default approach to use when neither of the others is defined.

**Comment by losintikfos** [comment]
@brunobelarmino Agree +1

**Comment by lafrech** [comment]
Fixed in master. @brunobelarmino, @ocean1, time to give it a try before the release ships.

**Comment by jzarob** [comment]
Is there any word for adding back support for MongoMock in? I saw it was removed in 2bb06df, but for a lot of people this could be a deal breaker for using flask and mongo who want to write good unittests.

**Comment by LaundroMat** [comment]
Hi @jzarob - I've been able to get things to work with pytest, flask and flask-mongoengine by adding this to my `conftest.py`

```
@pytest.fixture
def app():
    os.environ["MONGO_DB"] = "test"
    os.environ["MONGO_URI"] = 'mongomock://localhost'

    app = create_app()
    return app
```

This overloads the environment settings for when flask_mongo_engine.MongoEngine(app) is called in create_app().

**Comment by claradaia** [comment]
Hi @LaundroMat, could you provide more details? Perhaps your `create_app` code?

**Comment by LaundroMat** [comment]
Well, the only relevant code in `create_app()` is

```
    app = Flask(__name__)
    app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')
    csrf = CSRFProtect(app)
    app.config['MONGODB_SETTINGS'] = {
        'db': os.getenv('MONGO_DB'),
        'host': os.environ['MONGO_URI']
    }
    app.config['MONGODB_CONNECT'] = False  # open connection only on first database access
    db = MongoEngine(app)
```

You also need to include `app` as a parameter to every test function that touches the database. E.g.

    def test_create_model_instance(app):    # <- by including app, you're using the conftest app and thereby overriding the normal db connection
        # your test code.

**Comment by claradaia** [comment]
Thank you, @LaundroMat! Turns out my problem was I had not imported the main 'app' nor included the fixture as a parameter like you mentioned, so the database was never configured.

**Comment by mosesontheweb** [comment]
Hi,
I'm just a newbie using pytest for testing my code. Is there any full code example out there to see how a combination Flask/MongoEngine/mongomock could work? Snippets are not so meaningful to me, unfortunately.
Many thanks in advance for any answer, regards, Thomas
